### ISSUE TITLE
Problem With BetterFurnacesReforged on LAN Server

### ISSUE THREAD

**Issue by RapturedC** [Wilyicaro/BetterFurnacesReforged#1]
Hi! I have always loved the Better Furnaces Mod, and I put it on every modded world I play on.  However, I recently installed HWYLA on my new modded world, I was using the 1.12.2 alpha version, and when I place the Iron Furnace it crashed my world. So I looked on Forge and learned about its incompatibility.

Luckily, the "Release/Revamp" of the 1.12.2 version was available, and it said it worked with HWYLA, so I downloaded it. I first removed the alpha version of the mod from the world and loaded it with no BetterFurnaces. Then I closed it and reinstalled the Release/Revamp version. I could now craft and use the Better Furnaces with no issue. 

However, the person I'm playing my LAN world with gets this error message (attached) whenever they try to use the Furnace, no problem crafting, placing, or breaking the furnace, only when they try to use it. The weird thing is just that I have no problem. I went through the same steps I went through on their computer at the same time [removing alpha, running without BF, moving in revamp], and they have this issue and I don't.

Would really appreciate some help with this as I couldn't find anything about it online. Thank you so much for reading!

![unnamed](https://user-images.githubusercontent.com/88351411/127931726-0fe32679-feb1-4f93-acf3-11fbca4d28d3.png)

**Comment by Wilyicaro** [comment]
Really, it seems to be some mod bug in relation to network response, soon, after some testing, a fix will be released about it.

**Comment by RapturedC** [comment]
Alrighty, thanks so much! Really hope this is fixed soon, I really appreciate your quick response time!

This mod is definitely one of my favorites so thank you for developing and updating this mod, thank you!

**Comment by Wilyicaro** [comment]
You're welcome!  By the way, this issue has been resolved in the current release, so have a good game on LAN worlds or online :)
