### ISSUE TITLE
[Bug/Glitch] Crash when opening furnaces

### ISSUE THREAD

**Issue by Zeycox** [Wilyicaro/BetterFurnacesReforged#103]
**Mod Version-Minecraft Version**
1.20
Mod Loader Version

**Bug/Glitch Occurrence Context**
I crash when i open any furnaces
[latest.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11930309/latest.log)

**What happened wrong**
The game crashed

**Comment by Wilyicaro** [comment]
Did you look at the Factory API version? You have version 1.19.2, which is not loading properly because it is an incorrect version
