### ISSUE TITLE
[Bug/Glitch] 1.19.2 Crash When Trying to Open Furnaces

### ISSUE THREAD

**Issue by andw20** [Wilyicaro/BetterFurnacesReforged#105]
This is similar to issue #103 

I only have 4 mods installed

I tested out different versions of Factory API, Better Furnaces AND Architectury API

I've tested out
Architectury API versions 6.5.69 to 6.5.85
Factory API versions 0.1.6.1 to 0.1.8
Better Furnaces versions 0.2.1 to 0.2.5

The mod used to work completely fine before but now it brokie

**Mod Version-Minecraft Version**
1.19.2

Mod Loader Version
Fabric 1.19.2 
Version 0.14.21

**Bug/Glitch Occurrence Context**
Crash when opening furnaces

*Crash Report
[crash-2023-07-05_10.55.28-client.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11959353/crash-2023-07-05_10.55.28-client.txt)

[latest.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11959355/latest.log)

**What happened wrong**
Game crashes upon trying to open a furnace

**Comment by Wilyicaro** [comment]
Noting the crash you submitted, in this case it is an outdated version of BFR issue, but since you said you tested several versions of the mod and dependencies, I can only tell you to always use the latest, at least to send a crash report that can be fixed
