### ISSUE TITLE
WHY DID YOU REMOVE Advanced Ore Processing AND Advanced Efficiency Upgrade????

### ISSUE THREAD

**Issue by WOLF4X** [Wilyicaro/BetterFurnacesReforged#106]
Please can you atleast do like a different or like the same mod but just with the old items? Bcs i play this mod MAINLY for those upgrades but when you removed them now it's just plain yk? So please u dont really need to like update this one just copy the code and add the old items and like name it idk Better Furnaces Reforged 2.0 or something PLEASE im really just wanting to enjoy this mod (i play on 1.16.5 so please make it for 1.16.5 pls) thank you sir

**Comment by WOLF4X** [comment]
MAN im so sorry im just like REALLY dumb cause i was using jei and i was also using iron furnaces so i typed in "better furnaces" just but it didnt pull out the whole mod,... again im really sorry man

**Comment by Wilyicaro** [comment]
No problem, we all make mistakes :)
