### ISSUE TITLE
[Bug/Glitch] It crashes when i tried to open any mod furnace (1.20.1)

### ISSUE THREAD

**Issue by lKiMl0213** [Wilyicaro/BetterFurnacesReforged#108]
Well, i tried the iron furnace and the copper furnace (didn't test any other)
it crashes when i try to interact with. I can craft and place it, but cant open

full crash log:
[crash-2023-07-18_00.13.12-client.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/12075538/crash-2023-07-18_00.13.12-client.txt)

**Comment by Wilyicaro** [comment]
You are using the wrong minecraft version of Factory API, it's actually the 1.19.2, and you need to use the 1.20.1

**Comment by Wilyicaro** [comment]
The same issue #103
