### ISSUE TITLE
[Bug/Glitch] Ore Processing wont work with raw ores

### ISSUE THREAD

**Issue by GabrielXoxota** [Wilyicaro/BetterFurnacesReforged#109]
Minecraft version: 1.19.2
Mod version: BetterFurnaces-1.19.2-1.0.0-forge.jar
Loader: forge

the ore processing upgrade and the advanced ore processing upgrade wont work with raw ores but the ultimate one does, is this on purpose or is this a bug and how do i fix this? I tested on my instance with all my modpack and with another with just the betterfurnaces mod and on both of them i had the same problem.

**Comment by Wilyicaro** [comment]
You can see that there is a description for the upgrades, it being specified that it only works with block ores, which is why there is the Raw Ore Processing Upgrade, which was already discussed in #18

**Comment by GabrielXoxota** [comment]
> You can see that there is a description for the upgrades, it being specified that it only works with block ores, which is why there is the Raw Ore Processing Upgrade, which was already discussed in #18

ok thank you for answering my stupid question
