### ISSUE TITLE
Factory upgrade on extreme forge bug

### ISSUE THREAD

**Issue by Cynix32** [Wilyicaro/BetterFurnacesReforged#11]
As with the curseforge comment, here are the steps to reproduce said problem
LEGEND:
B = Barrel
F = Extreme Forge
H = Hopper

Arrange it this way:
B
F
H
B

First, input factory upgrade, advanced fuel upgrade, liquid fuel upgrade or energy upgrade
For the factory setup:
output at bottom
imput at top
none at all horizontal sides

AUTO-INPUT ON (the critical part )
AUTO-OUTPUT OFF (also critical to reproducing this bug)

1. input 3+ stacks of smeltable items such as ores in the barrel at the top of the forge
2. the forge will auto-input the said ingredients
3. the input slots of the forge get filled
4. HOWEVER, the hopper will pull out the items from the third input slot of the forge, that is the bug. The hopper should not pull out of any of the input slots because it is not supposed to. Moreover, the factory was configured in such a way that auto-output is off, and only auto-input is on. What's weird is that the hopper will only specifically pull out the items on the third input slot; the first two input slots are unaffected by this bug.
5. check that some of the items that were meant to be smelted/placed in the third input slot end up in the bottom barrel unsmelted.

Note that this also happend with the ultiamte furnaces bfr addon mod.

**Comment by Wilyicaro** [comment]
I fixed this bug in current version 1.4.6 :)
