### ISSUE TITLE
[Bug/Glitch] Rendering Screen Crash

### ISSUE THREAD

**Issue by Savior10K** [Wilyicaro/BetterFurnacesReforged#110]
*Crash when adding an energy upgrade while furnace/forge is using fuel*

**1.0.0-Minecraft Version 1.20.1**

Forge  47.1.3

**Crash with rendering screen error when adding an energy upgrade to diamond forge while it is still using fuel**

*https://mclo.gs/a8kn0Eb

**Comment by Wilyicaro** [comment]
If you don't want to wait for a new BFR update, you can downgrade the Factory API version to 0.1.8, it will work normally. 
It's an issue related to the new Factory API update that made major changes

**Comment by LokeYourC3PH** [comment]
+1, same issue. I can wait since I can just use other Furnaces that don't have said issue for now, and my Extreme Forge is automated anyways. Was rather unexpected though, having BFR crash out of nowhere 😂
