### ISSUE TITLE
[Crash] 1.16.5 Dedicated Server crashing when opening any betterfurnaces furnace/forge

### ISSUE THREAD

**Issue by xDBurrachaxD** [Wilyicaro/BetterFurnacesReforged#111]
**Mod Version-Minecraft Version**

Mod 1.0.1-Forge on Minecraft 1.16.5

**Mod Loader Version**

Forge 36.2.35

**Bug/Glitch Occurrence Context**

When trying to open the furnace/forge the server crashes

**Crash Report**

[crash-2023-07-29_09.17.34-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/12207222/crash-2023-07-29_09.17.34-server.txt)

**Comment by Wilyicaro** [comment]
Fixed in 1.16.5-1.0.2 :)

**Comment by xDBurrachaxD** [comment]
First, thanks for the hard work with that mod, one of my favorite furnace mod, if not the number one for me

But yeah, it's fixed when you open it without anything surrounding, but now if there is another furnace/machine/generator on the side and you open it, it still crashes

Also the textures are not loading, they are with the "missing Texture block (Magenta/Black Grid block). If you need something to fix that, just ask me

**Crash Report:**

[crash-2023-07-31_07.50.25-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/12214245/crash-2023-07-31_07.50.25-server.txt)

**Comment by xDBurrachaxD** [comment]
> Fixed in 1.16.5-1.0.2 :)

First, thanks for the hard work with that mod, one of my favorite furnace mod, if not the number one for me

But yeah, it's fixed when you open it without anything surrounding, but now if there is another furnace/machine/generator on the side and you open it, it still crashes

Also the textures are not loading, they are with the "missing Texture block (Magenta/Black Grid block). If you need something to fix that, just ask me

Crash Report:

[crash-2023-07-31_07.50.25-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/12214304/crash-2023-07-31_07.50.25-server.txt)

**Comment by Wilyicaro** [comment]
It is certainly a problem resulting in another, because of the problem observed in the crash report, there is also the error in loading the models of the furnaces and forges
And I'm glad to see you helping with the development of the mod :)

**Comment by Wilyicaro** [comment]
This will be fixed in 1.16.5-1.0.3 version
