### ISSUE TITLE
[Bug/Glitch] Generator Upgrade + CREATE Mod/Pipez mod fluid pipes will not add water

### ISSUE THREAD

**Issue by MichaelMichelle2** [Wilyicaro/BetterFurnacesReforged#113]
*Italic* = Optional

**Mod Version-Minecraft Version** 1.20.1

Mod Loader Version 47.1.40

**Bug/Glitch Occurrence Context**
Occurs 100% of the time...

*Crash Report

**What happened wrong**
The generator will not automatically fille up with water (the furnace with generator upgrade) with the CREATE or PIPEZ mod, it worked on my flat world, but in my survival world it isn't working at all. No water is going inside at all, and the water is coming from a source or ender tanks, neither work.

EDIT: Occurs when using the fuel liquid upgrade and when lava is stored inside, the water will not fill up whatsoever, not even with a tiny amount in.

**Comment by Wilyicaro** [comment]
Thanks for reporting, I'm planning to make a more efficient system for the Factory Upgrade with the possibility to exactly configure the fluids and also the energy sides, but for now I will simply change the sides that are for the XP Upgrade, which can't be used with the Generator Upgrade, for the water tank.
