### ISSUE TITLE
[Bug/Glitch] Furnace error textures

### ISSUE THREAD

**Issue by ZenDemenos** [Wilyicaro/BetterFurnacesReforged#114]
*Italic* = Optional

**Mod Version-Minecraft Version** 1.16.5

Mod Loader Version 36.2.34 and 36.2.39

BetterFurnaces-1.16.5-1.0.3-forge

**Bug/Glitch Occurrence Context**
Arises at every entrance to the world, at the entrance to any world

**What happened wrong**
Furnaces textures don't work when entering the world. Work only after reloading a set of resources in the world.

The image shows an iron furnace and an iron forge:
![Error](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/141748088/11d682e3-3d25-4430-84ff-256d3197d071)

**Comment by Wilyicaro** [comment]
Are you using other mods with the BFR and its dependencies? 
This model loading error never happened to me

**Comment by Wilyicaro** [comment]
This error already happened with other players in different versions of the mod, as in #83

**Comment by ZenDemenos** [comment]
No, I don't use any other mods. Only the BFR, Architectury Api and Factory Api are required for it to work. Occurs after starting minecraft and entering any world. The error disappears after restarting the resource pack and everything works correctly in any worlds.

I'm attaching the logs, maybe it will help:
[latest.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/12308788/latest.log)

**Comment by Wilyicaro** [comment]
Is it still happening in the last update? Because it never happened to me, so I can't test if the patch works

**Comment by ZenDemenos** [comment]
I apologize for answering just now. After checking version 1.04, the problem no longer occurs. The only thing missing in this version is the updated Russian translation that I sent, but everything else is fine.

**Comment by Wilyicaro** [comment]
Sorry for forgot your updated Russian translation, in the next version it'll be present
