### ISSUE TITLE
[Bug/Glitch] crash with optifine

### ISSUE THREAD

**Issue by RomulloSousa1** [Wilyicaro/BetterFurnacesReforged#116]
### Better Furnaces Reforged Version

1.12.2 - 1.5.4

### Mod Loader Version

Forge 14.23.5.2860

### Bug/Glitch Occurrence Context

I'm trying to add Optifine to my modpack, but it's crashing with Better Furnaces Reforged.

### Crash Report

https://pastebin.com/raw/KpkibUCZ

### What happened wrong?

The situation is as follows: I reinstalled the modpack and everything worked fine. However, when I exit the Multiplayer server, it crashes. To get it working again, I have to reinstall the modpack once more.

What could this be?

https://cdn.discordapp.com/attachments/1143009287690534982/1143012276840964096/image.png

**Comment by Wilyicaro** [comment]
For now, try to disable the update checker in the BFR config file

**Comment by RomulloSousa1** [comment]
@Wilyicaro I figured out how to fix it. Since I'm not from the United States, I use another language in minecraft, and this is probably the cause of the error. When I put my minecraft in English, it didn't give the error anymore. I don't know if it's really related to BFR, but it's here in case anyone else has the same problem :D

**Comment by Wilyicaro** [comment]
Very strange bug, but thanks for sharing your way to fix it! Whatever I will close this issue
