### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by SilveredArrows** [Wilyicaro/BetterFurnacesReforged#117]
### Better Furnaces Reforged Version

1.0.4

### Mod Loader Version

Forge 36.2.39

### Bug/Glitch Occurrence Context

I added Better Furnaces to my server with PMMO 3.69.0 and server don`t want to start

### Crash Report

https://gist.github.com/SilveredArrows/b6f172c66243001cc0f7ba627ea569cb

### What happened wrong?

Crash during server and minecraft client start up.

**Comment by Wilyicaro** [comment]
It's a dependency version conflict. 
Probably Project MMO changed its version numbering, so you can try modify PMMO version in mods.toml file inside META-INF folder, if you can't wait for a new update
