### ISSUE TITLE
[Bug/Glitch] Crash when opening BFR Furnace GUI

### ISSUE THREAD

**Issue by LokeYourC3PH** [Wilyicaro/BetterFurnacesReforged#118]
### Better Furnaces Reforged Version

BetterFurnaces-1.20.1-1.0.2-fabric

### Mod Loader Version

Fabric Loader 0.14.22

### Bug/Glitch Occurrence Context

Opening the Furnace's GUI will lead to a client crash.

[crash-2023-08-28_13.10.01-client.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/12450143/crash-2023-08-28_13.10.01-client.txt)

### Crash Report

Check above.

### What happened wrong?

-

**Comment by Wilyicaro** [comment]
Incompatibility issue with the new update of Factory API(1.20-1.1.2)
The new BFR version will fix this problem.
