### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CloWnicide** [Wilyicaro/BetterFurnacesReforged#119]
### Better Furnaces Reforged Version

1.20.1-1.0.3

### Mod Loader Version

Forge 47.1.3

### Bug/Glitch Occurrence Context

Trying to put a furnace down crashes the game.

[crash-2023-09-16_11.37.29-client.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/12641398/crash-2023-09-16_11.37.29-client.txt)

### What happened wrong?

Trying to put a furnace down crashes the game.

**Comment by Wilyicaro** [comment]
Clearly, this is a RailCraft Reborn incompatibility with BFR, probably it can be fixed, but it's not a real BFR issue.
