### ISSUE TITLE
Icons Bugged on REI interface.

### ISSUE THREAD

**Issue by XxFallenAngelxX** [Wilyicaro/BetterFurnacesReforged#12]
![2021-12-02 19_30_47-Greenshot](https://user-images.githubusercontent.com/50654704/144482084-18d6b995-fd17-459f-8c8f-31c3164dd543.png)

WHen i use the new version 1.18 with REI, the Icons of certain furnaces are bugged in the REI window.

**Comment by Wilyicaro** [comment]
This bug has already been fixed in the new builds, but I will release it to the public as soon as the JEI is updated to 1.18
