### ISSUE TITLE
[Bug/Glitch] Top and Bottom don't work as intended

### ISSUE THREAD

**Issue by NattoRiisa** [Wilyicaro/BetterFurnacesReforged#120]
### Better Furnaces Reforged Version

BFR [Fabric] 1.20.1-1.0.3

### Mod Loader Version

Quilt Loader 0.21.0 beta 3

### Bug/Glitch Occurrence Context

This may be a mod conflict with the bunch of mods I have, idk.

### What happened wrong?

i tried clicking on the top and bottom
got nothing

https://github.com/Wilyicaro/BetterFurnacesReforged/assets/52566765/0c649807-4414-4ed8-8d54-23a7c6273750

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue, it'll be fixed in the new update
