### ISSUE TITLE
[Bug/Glitch] Piping Upgrade gives redstone signal configuration instead of side configuration

### ISSUE THREAD

**Issue by neinome** [Wilyicaro/BetterFurnacesReforged#121]
### Better Furnaces Reforged Version

1.19.4-1.0.1

### Mod Loader Version

Fabric 0.14.22

### Bug/Glitch Occurrence Context

Placing Piping Upgrade into any of the Better Furnaces and checking configuration.

### Crash Report

N/A

### What happened wrong?

First image shows the Redstone Signal Upgrade's configuration interface, which works as expected. The second shows what happens when the Piping Upgrade is inserted into the furnace instead of the Redstone Signal Upgrade, and it has the same redstone signal interface instead of the side configuration.  The third image is the Factory Upgrade, which is the only upgrade that shows the side configuration.

![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/7586178/52ecdc7b-1ce5-41c4-9765-9e5faf0a2266)
![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/7586178/27c71d24-c559-4e9e-bb12-511e2e241b3e)
![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/7586178/f8fc405a-f4ff-4731-9ed4-2531c8c50aee)

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue that I missed.
This will be fixed in the 1.19.4-1.0.2 version
