### ISSUE TITLE
[Bug/Glitch] Inseting lava into Better Furnaces with pipes does nothing

### ISSUE THREAD

**Issue by neinome** [Wilyicaro/BetterFurnacesReforged#122]
### Better Furnaces Reforged Version

1.19.4-1.0.1

### Mod Loader Version

Fabric 0.14.22

### Bug/Glitch Occurrence Context

Attach a pipe/tank with lava on a side that automatically inputs fuel into furnace.

### Crash Report

N/A

### What happened wrong?

Liquid fuels do not insert into a Furnace that should be automatically inputting fuels.  Adjacent tanks do not have liquid removed from them, nor do pipes input into fuel slot.

Pipes mod: (not that there are many choices for Fabric ATM)
Simple Pipes, and its addon PipesPlus.

**Comment by Wilyicaro** [comment]
Try using fluid pipes at the top or bottom of the furnace, and if it doesn't works wait for an update of the Factory API
