### ISSUE TITLE
[Bug/Glitch] Newer version of BFR causes crash on placing furnace, causes world to be unloadable (1.16.5)

### ISSUE THREAD

**Issue by etmoonshade** [Wilyicaro/BetterFurnacesReforged#124]
### Better Furnaces Reforged Version

1.16.5-1.0.4-forge

### Mod Loader Version

Forge 36.2.39

### Bug/Glitch Occurrence Context

The first crash log is the one that was generated when I started a new game with BetterFurnaces-1.16.5-1.0.4 installed (the most recent version, dated 17 Aug 2023.) The game crashed immediately upon placing the furnace.

The second one is directly after the crash when placing the furnace, and I tried restarting the game with no changes.

The third one is after I'd reverted to BetterFurnacesReforged-1.16.5-2.0.0 (this allowed me to load the game with the furnace that was previously crashing) and played for a while, and then tried updating BFR to the most recent version (1.0.4) again.

It's definitely a regression - I actually tried a few other versions on the way back to 2.0.0 - but the crash logs don't make sense. The last log, after upgrading the version again, doesn't even _mention_ BFR, but the update is the change there. Weirdest thing.

### Crash Report

https://www.dropbox.com/scl/fi/qa2bpwfetfawaym4w7esu/crash-reports-BFR-issue124.zip?rlkey=d91d6ays89ayhc108kraffmrk&dl=0

### What happened wrong?

I think I kinda covered this in the first part, but game go crashy. Very bad. :(

Side note - this is a modpack I've been messing with, so it should be easy enough to test in situ. The pack's called Epsilon's CozyCraft, and you can grab it off CurseForge. In the meantime, I'll see what I can strip out of the modpack to see if the crash goes away, because I *can* successfully use BFR when it's the only mod that exists in the pack.

**Comment by etmoonshade** [comment]
Okay, after a LOT of fiddling:
Looks like something's happening with Cooking For Blockheads - minimal reproducible crash log/mod list here:
https://www.dropbox.com/scl/fi/z4x3sxe1lbfnnz5ydidgj/crash-2023-09-23_18.50.47-client.txt-BFR-issue124.zip?rlkey=4qu610cnwimrzsym647u56l7v&dl=0

Now, even with CFB unloaded, I'm having another crash (which explains why this was giving me fits trying to find the ONE mod that's causing troubles...) - in the second instance, it appears that when CC: Tweaked and More Red are loaded, the game _also_ crashes. Minimal reproducible crash log/mod list here:
https://www.dropbox.com/scl/fi/8n9tsu0ct0xv6vvezfacs/crash-2023-09-23_19.06.38-client.txt-BFR-issue124.zip?rlkey=vl3qhj1ix5076gy3qgywz1pww&dl=0

Amusingly, the game runs fine with ONLY CC or ONLY More Red loaded with BFR. Go figure.

**Comment by Wilyicaro** [comment]
Firstly, thanks for reporting this crash issue :)
This is apparently an incompatibility of some mods that you used, like CFB, which attach its own capabilities to some registered block entities. BFR uses Mixin to add Forge capabilities compatibility in this version, that creates this incompatibility.
This will be fixed in the new parity update

**Comment by etmoonshade** [comment]
Good to know that it's something that's fixable, at least. I'll keep an eye out for the update. Thanks!
