### ISSUE TITLE
[Visual/Glitch]

### ISSUE THREAD

**Issue by EvoMods** [Wilyicaro/BetterFurnacesReforged#125]
### Better Furnaces Reforged Version

1.20.1-1.0.3

### Mod Loader Version

Forge 47.2.0

### Bug/Glitch Occurrence Context

When placing any of the Forges; The TOP of the block is facing towards the player. This seems to only occur when placing a block down while on the same Y-dim as the player. If a player is at a higher Y-dim the block is placed with the RIGHT side facing the player; See attachment for example.

![debugg_furnaces](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/145947617/c506d3df-f132-4a67-88dc-e18c77f65808)

### What happened wrong?

JAVA 17.0.8 (64bit)
Minecraft 1.20.1
Forge 47.2.0
Resourceful Lib 2.1.11
Botarium 2.2.0
Jade 11.5.1
Just Enough Items 15.2.0.27
WitherUtils 1.20.1-1.0.32
OceanTech 1.0.2
GeckoLib 4.2.3
Better Furnaces Reforged 1.0.3
Architechtury 9.1.12
Factory API 1.1.3
FTB Library 2001.1.3
FTB Teams 2001.1.4
FTB Chunks 2001.2.2

Let me know if theres any other information you might need - Love the concept and idea of the mod! (Could use a texture update tho! Lol)

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue :)
The front, back, left, right, top and bottom are relative to the model of the forge, that is, these orientation changes with the facing of the forge, as an furnace, it's front(top in the case of forge, cuz it doesn't have an unique front in the model) will always be the direction of the facing block state.
