### ISSUE TITLE
[Request] Fabric 1.18.2 Port

### ISSUE THREAD

**Issue by PlayfulPiano** [Wilyicaro/BetterFurnacesReforged#127]
### Better Furnaces Reforged Version

N/A

### Bug/Glitch Occurrence Context

Hi, I'm aware this isn't the proper formatting for this issue request, but there isn't one available for suggestions.

I wanted to ask if it was at all possible to port this mod to fabric 1.18.2. Currently, there are only three other mods to my knowledge that are based on a "furnace upgrade" concept for Fabric 1.18.2 (Fabric Furnaces, Iron Furnaces, and Furnace MK2), and of those 3:
- Fabric Furnaces has none of the added features that benefit a more tech/modded playthrough (specific side input/output/fuel, upgrades, xp storage)
- Iron Furnaces has no XP storage system, a severe input bug where items that are meant to be put into the input slot also go into the fuel slot once the input slot is at max capacity, and the support for the fabric edition seems completely dead/abandoned (no updates past 1.18)
- Furnace MK2 seems to be still in an early stage, especially for fabric (listed as alpha), and also seems to be abandoned/not supported.

I've been using Iron Furnaces for a bit but I would really want to switch over to this mod in my personal modpack, but sadly it's only for forge at this version + I have multiple mods which don't have 1.19 versions available.

I can understand not wanting to backport features - I'm completely fine with just having a straight port of the 1.18 forge version (even excluding the ultimate furnace addon if you want!). I just would really hope you could potentially do this.
Thank you.
-Piano

### What happened wrong?

N/A

**Comment by Wilyicaro** [comment]
Thanks for requesting this port, I hadn't ported to 1.18.2 yet because no one asked previously, and I had planned additions and fixes for the other versions.
Probably in the next weeks I can complete this port.

**Comment by PlayfulPiano** [comment]
Thank you so much! Can't wait to switch when it's done. Possibly reply here when you do finish the port so I can get notified, if you don't mind.

**Comment by Wilyicaro** [comment]
> Thank you so much! Can't wait to switch when it's done. Possibly reply here when you do finish the port so I can get notified, if you don't mind.

Finally, I finished the port, it's now available for download, and again, thanks for requesting ;)

**Comment by PlayfulPiano** [comment]
Thank you so much for this!

**Comment by Wilyicaro** [comment]
You're welcome 😁
