### ISSUE TITLE
[Bug/Glitch] Copper Furnace weakens fuel efficiency.

### ISSUE THREAD

**Issue by PlayfulPiano** [Wilyicaro/BetterFurnacesReforged#128]
### Better Furnaces Reforged Version

1.20.1-1.1.1

### Mod Loader Version

Forge 47.2.1

### Bug/Glitch Occurrence Context

When using the Copper furnace, fuel items across the board have a slightly worse burn efficiency than vanilla.

I haven't tested it yet with other furnace types yet, and it happens regardless of config setting for speed.

### What happened wrong?

Examples:
2 Sticks - Expected to smelt 1 item, ends up smelting like 99% of the way before the fuel burns up and ends up not smelting the item.
8 Coal/Charcoal - Expected to smelt 64 items, ends up smelting only 63 items and around 3/4ths of the way to the 64th item.

**Comment by PlayfulPiano** [comment]
Ok quick update, it might be related to default speed settings actually. I changed the tick rate from 175 to 180 (which is divisible easily by 20t/1s), and now I'm not experiencing that issue anymore.

That or there might be some inconsistency if interacting with server lag? I'm unsure.

**Comment by Wilyicaro** [comment]
You are right, the problem is exclusivelly related to integer division that maintains the fuel efficiency proportional across all furnaces. Probably the only viable solution for now is to change the furnace tier speed to a number with accurate division result by 200, as 180.

**Comment by PlayfulPiano** [comment]
This is probably based on whether the decimal goes to the thousandths place, if I were to take a guess, based on how other furnace mod logic from what I remember didn't have issues at like, super low even number tick rates.

If you want a suggested default change, this is what I had all my furnaces set to:
Copper - 180
Iron - 160
Steel - 140
Gold - 120
Amethyst - 100
Diamond - 64
Platinum - 32
Netherhot - 16
Extreme - 8
Ultimate - 4


Pretty sure there's also like a 4t limit for hopper item movement anyways so realistically keeping ultimate at 4 would be pretty good for vanilla parity.

**Comment by Wilyicaro** [comment]
Update: I fixed these issues with furnace tiers with speeds not divisible by 200 in the last versions.
