### ISSUE TITLE
Adjusting the configuration of a furnace crashes game

### ISSUE THREAD

**Issue by neinome** [Wilyicaro/BetterFurnacesReforged#129]
### Better Furnaces Reforged Version

1.19.4-1.1.1

### Mod Loader Version

Fabric 0.14.22 & Fabric 0.14.24

### Bug/Glitch Occurrence Context

Attempting to adjust the configuration of a furnace causes a Java IndexOutOfBounds exception, and crashes.
Tried with Fabric Loader 0.14.22 / API 0.87.0  and Fabric Loader 0.14.24 / API 0.87.2

![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/7586178/d8079e5c-5429-4078-be94-6e69b61c6ebc)
![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/7586178/1e2b0e65-38b8-4566-ae70-256e12a03461)

### What happened wrong?

Game crashed when trying to change furnace piping configuration

**Comment by Wilyicaro** [comment]
Thanks for reporting this issue, I already discovered the solution, probably I'll fix it soon.
