### ISSUE TITLE
Extreme Forge Energy Upgrade not working

### ISSUE THREAD

**Issue by cmar7945** [Wilyicaro/BetterFurnacesReforged#13]
Mod Version 1.18-1.1

Minecraft Version 1.18

Forge Version 38.0.14

Bug

What happened

When supplying an Extreme Forge with energy, while containing the Energy Upgrade, power does not seem to be accepted by the machine on any side.

**Comment by Wilyicaro** [comment]
I'm going to do some tests in relation to this, but I'll advance that I didn't carry out tests in relation to this because of the lack of power production mods and cables to do the test on 1.18

**Comment by cmar7945** [comment]
Im currently using the following mods for power production and cables respectively: ExtremeReactors2 and Pipez if that helps!

**Comment by Wilyicaro** [comment]
Thank you very much for the report, I fixed the  energy Extreme Forge bug in the new mod version , which to make matters worse was resetting the inventory content every time I reloaded the world.
