### ISSUE TITLE
BFR 1.1.1 crash when placing furnace in world (1.16.5)

### ISSUE THREAD

**Issue by Zelly9191** [Wilyicaro/BetterFurnacesReforged#130]
### Better Furnaces Reforged Version

1.16.5-1.11

### Mod Loader Version

forge 36.2.34

### Bug/Glitch Occurrence Context

placing the extreme furnace in the world crashes the game.
using the latest 1.16.5 of bfr

### Crash Report

https://pastebin.com/RJ334XHa

### What happened wrong?

haven't checked but the world might be toast.

**Comment by Zelly9191** [comment]
If there's anything I can do to provide more information let me know

**Comment by Wilyicaro** [comment]
Probably it is an incompatibility with the Cooking For Blockheads mod, I'll test this and tell you if it is a BFR issue.

**Comment by Wilyicaro** [comment]
This dedicated server crash was fixed in the last update, 1.16.5-1.1.2.
