### ISSUE TITLE
[Bug/Glitch] - XP upgrade cannot be used.

### ISSUE THREAD

**Issue by ElectroArtifex** [Wilyicaro/BetterFurnacesReforged#132]
### Better Furnaces Reforged Version

1.20.1-1.1.1

### Mod Loader Version

Fabric

### Bug/Glitch Occurrence Context

Cannot insert xp tank upgrade even with config set to Kibe and Kibe Utils installed. 

Reopening issue since it closed due to a clear misunderstanding. Despite the tooltip suggesting that the configured mod is recognized, the XP upgrade still does not work. 
More information here: [https://github.com/Wilyicaro/BetterFurnacesReforged/issues/131](url)

### What happened wrong?

Despite the tooltip suggesting that the configured mod is recognized, the XP upgrade still does not work.

**Comment by Wilyicaro** [comment]
Are you using Forge Config API Port mod? I'm sure this is working.
https://clipchamp.com/watch/aFYp3CglLjO

**Comment by ElectroArtifex** [comment]
After watching your video, I finally figured the issue out-- the XP tank upgrade MUST be inserted first, or it cannot be inserted. If you have a blasting upgrade in the furnace already, it will not apply. (This might be useful in a note somewhere if this is intentional). Thank you for your time in helping me troubleshoot.
