### ISSUE TITLE
[Github] Add documentation for the Cobblestone Generator.

### ISSUE THREAD

**Issue by PlayfulPiano** [Wilyicaro/BetterFurnacesReforged#134]
### Better Furnaces Reforged Version

N/A

### Mod Loader Version

N/A

### Bug/Glitch Occurrence Context

I just crafted a cobblestone generator and I've now realized that there isn't any documentation for how the generator works. Specifically, in regards to the coal and ingot slots on the left, & how the block auto outputs items.

### What happened wrong?

N/A

**Comment by Wilyicaro** [comment]
As the Cobblestone Generator isn't a main feature of the mod, and its use is very simple, I had think that this is not needed. 
Whatever, I'll update the Wiki with these miscellaneous features.
