### ISSUE TITLE
[1.18] Furnace to Iron Furnace Upgrade Deletes Furnace

### ISSUE THREAD

**Issue by Boomflex** [Wilyicaro/BetterFurnacesReforged#14]
BFR: BetterFurnacesReforged-1.18-1.2.jar
Forge: 38.0.16

Shift right click with the upgrade on a normal furnace makes the furnace disappear.

Other upgrades seem to work fine.

https://streamable.com/huh60j

**Comment by Wilyicaro** [comment]
This error is very weird, could you test this in version 1.17 to see if the same occurs?  Please, if possible show any error you have on the game console

**Comment by Wilyicaro** [comment]
It was such a simple bug in the code that I will release this fix as soon as I make major changes to the mod.
This fix will be released soon on CurseForge
