### ISSUE TITLE
[Bug/Glitch] Energy Upgrade tooltip mistake

### ISSUE THREAD

**Issue by PlayfulPiano** [Wilyicaro/BetterFurnacesReforged#140]
### Better Furnaces Reforged Version

1.20.1-1.1.1

### Mod Loader Version

Forge 47.2.5

### Bug/Glitch Occurrence Context

The tooltip for the energy upgrade is incorrect, stating it's for the extreme forge.
![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/3158887/c09c85c0-c480-4114-a50a-49bb2972407b)

### What happened wrong?

It should just state that it allows usage from energy in general.

**Comment by Wilyicaro** [comment]
Thanks for sharing this translation mistake, probably I have changed it in some version but with so many versions I forgot.
In past versions, as seen in this tooltip,  it was only possible to use the Energy Upgrade in forges.
