### ISSUE TITLE
[Bug/Glitch] AE2 Import Bus causes logs to enter the fuel slot if the input slot reaches max capacity.

### ISSUE THREAD

**Issue by PlayfulPiano** [Wilyicaro/BetterFurnacesReforged#141]
### Better Furnaces Reforged Version

1.20.1-1.1.1

### Mod Loader Version

Forge 47.2.5

### Bug/Glitch Occurrence Context

When using an AE2 import bus to import wooden logs into a furnace (top side), once the top slot reaches maximum capacity of 64 logs, it will then start importing logs into the fuel slot if left open. This behavior does *not* occur with vanilla furnaces.

What should be the case is that once the top input slot is full, logs will stop importing into the furnace, assuming that the only location of a log based import bus is on the top side (and is set as such under the piping upgrade).

### What happened wrong?

N/A

**Comment by Wilyicaro** [comment]
The fuel slot is considered a input slot and output slot with the Factory Upgrade, as a way of simplify some processes, this is not a bug and obviously is proposital.

**Comment by PlayfulPiano** [comment]
I've had this issue occur with and without the factory upgrade for reference. Actually I tried using the factory upgrade as a means to fix it but that didn't work out.

**Comment by Wilyicaro** [comment]
I don't know if this is your case, but when I wrote Factory Upgrade I mean all upgrades with this same function, as the piping upgrade. If you are sure that you used it without any factory-like upgrade, it is indeed a bug, but it is probably related to how AE2 Import Bus works

**Comment by PlayfulPiano** [comment]
I asked over on AE2's side and they mentioned it usually comes from the furnace implementation?
![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/3158887/b9d48acf-5a0b-4135-9f6c-a3d93314a8f2)

**Comment by Wilyicaro** [comment]
I tested with the same mods you listed and averything is working correctly, when a factory-like upgrade isn't present in the furnace, the top side only accept items in the input slot. The first thing I noticed is that I think you are talking about the Export Bus, yes it is a little confusing, but I could be wrong.

**Comment by PlayfulPiano** [comment]
yeah sorry I meant the export bus (honestly the export/import terms always felt like they should be flipped).

and huh, yeah you're right. I swear I tested it earlier without any piping type upgrade and it didn't work properly. But I just tried it now and there's no issue. Never mind I guess.
