### ISSUE TITLE
[Bug/Glitch] Unable to extract Fluid XP from furnace using an AE2 P2P Tunnel & Mob Grinding Utils XP Tank.

### ISSUE THREAD

**Issue by PlayfulPiano** [Wilyicaro/BetterFurnacesReforged#142]
### Better Furnaces Reforged Version

1.20.1-1.1.1

### Mod Loader Version

Forge 47.2.8

### Bug/Glitch Occurrence Context

The [P2P Tunnel](https://guide.appliedenergistics.org/1.20.1/items-blocks-machines/p2p_tunnels) is an item in Applied Energistics 2 which allows for the transfer of energy, xp, items, etc. from one point to another within a network. This functions fine with the Energy attunement when connecting the furnace with a solar flux reborn solar panel for energy transfer. But I'm trying to do the same with the fluid XP stored within BFR, as I don't believe I have another method of withdrawing that fluid.

I tried connecting both with a fluid P2P tunnel both on the same frequency, and it doesn't drain the XP.
![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/3158887/8d88beb7-8eb2-48dd-b19f-b2d0ec9ec698)
![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/3158887/4e354401-855c-4ee5-9019-340a228915e0)
![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/3158887/2c65fdce-8759-4afb-b707-f228ac987c93)

### What happened wrong?

The XP from BFR should be able to get drained and then deposited into the XP drain singularity tank, to my understanding of how each items in question works.

**Comment by Wilyicaro** [comment]
You know how it works, right? It is like you place a XP Drain Singularity Tank on the side of the furnace, nothing will occur as the furnace don't output automatically the liquid XP to the nexts tanks.

**Comment by Wilyicaro** [comment]
You need to use a tube or anything from a mod that extract the fluid from the next tanks(the furnace, in this case).
