### ISSUE TITLE
[Bug/Glitch] Auto-Input on Forge = Deleted Items

### ISSUE THREAD

**Issue by EarendelJWST** [Wilyicaro/BetterFurnacesReforged#144]
### Better Furnaces Reforged Version

1.20.1-1.1.1

### Mod Loader Version

Fabric Loader 0.15.1

### Bug/Glitch Occurrence Context

Turning Auto-Input on in a Forge with no items in it will delete most items from input containers.

### Crash Report

N/A

### What happened wrong?

To recreate:
1. Use a Forge with Factory Upgrade or Auto-Input upgrade. Ensure that Auto-Input is set to "OFF"
2. Place several stacks--4 or more--of smeltable items into an adjacent container; I've specifically been using chests. Seems to occur primarily when there is a mix of smeltables.
3. Now set Auto-Input to "ON". The Forge will pull in 1-3 stacks of items and delete all other items from the input containers.

I have been able to replicate this with both the Extreme Forge and Ultimate Forge. This doesn't seem to occur with furnaces. This also happens with inputting fuel; it seems the forge is "overdrawing" what it can take in and deleting anything that's pushed to the back of the queue. I originally discovered this after mining for several hours and having an entire double chest full of ores delete itself. Giving the forge some fuel/ores before turning Auto-Input on seems to circumvent this, but I have had the deletion occur on subsequent inputs.

**Comment by Wilyicaro** [comment]
Sorry for the late reply, and for the ores too, I will fix it in the next version of the mod
