### ISSUE TITLE
Storage Upgrade

### ISSUE THREAD

**Issue by Notlucky101** [Wilyicaro/BetterFurnacesReforged#145]
### Better Furnaces Reforged Version

1.19.2

### Mod Loader Version

1.19.2-112

### Bug/Glitch Occurrence Context

No recipe???

### What happened wrong?

No recipe

**Comment by Wilyicaro** [comment]
Thank you very much for reporting this issue, probably I forgot the recipe when I add the Storage Upgrade. It will be fixed in the next version of the mod
