### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by OJGaming** [Wilyicaro/BetterFurnacesReforged#147]
### Better Furnaces Reforged Version

1.20.1

### Mod Loader Version

Fabric 0.15.3

### Bug/Glitch Occurrence Context

Ore Processing Upgrade doesn't seem to work at all. I put the upgrade in the upgrade slot on a copper and iron furnace and then tried to smelt gold and iron and it didn't duplicate my yields at all. Or is the Raw Ore processing upgrade meant to be used? If this is the case that's not clear at all and is very confusing.

### What happened wrong?

Ore Processing Upgrade seems flawed.

**Comment by Wilyicaro** [comment]
Look at #109 and when it firstly was discussed #18.
