### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by MyHa99Mad** [Wilyicaro/BetterFurnacesReforged#149]
### Better Furnaces Reforged Version

betterfurnacesreforged-1.16.5-1.9.8

### Bug/Glitch Occurrence Context

I played in the mods build (A look into the past 1.16.5) and got a crash

### What happened wrong?

it crashes immediately after processing the ore, breaking the preservation completely, does not allow it to enter and throws it away. if you delete a folder (C:\...\.minecraft\saves\*name world*\region) or upload a backup, it works fine.
[tl console.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/13928934/tl.console.log)
[crash-2024-01-13_21.56.08-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/13928935/crash-2024-01-13_21.56.08-server.txt)

**Comment by Wilyicaro** [comment]
Unfortunately, I don't support the versions prior the Multi mod loader versions anymore, but it's a known issue with the incorrect handled compatibility with  PMMO
