### ISSUE TITLE
Startup CRASH/modloading issues with Ultimate Furnaces and the latest Better Furnaces Reforged.

### ISSUE THREAD

**Issue by Cynix32** [Wilyicaro/BetterFurnacesReforged#15]
The latest versions of BFR is incompatible with Ultimate Furnaces Addon. Specifically, forge throws a NoClassDefFoundError. Some of the classes that Ultimate Furnaces depend on BFR were probably changed. 

log: https://pastebin.com/dX1SV93r

Forge 36.2.20
MC 1.16.5
Java 8
BetterFurnacesReforged-1.16.5-1.6.1.jar
Ultimate-Furnaces-BFR-1.16.5-1.1.1.jar

**Comment by Wilyicaro** [comment]
I am very well aware of this, yesterday an update of the addon was planned to be released for all currently supported versions of the mod
