### ISSUE TITLE
More compatibility  with liquid fuels 

### ISSUE THREAD

**Issue by DaffodilClaw** [Wilyicaro/BetterFurnacesReforged#150]
I would like to suggest that it be possible to use liquid fuels from other mods, such as seed oil from Create: Crafts & Additions

**Comment by Wilyicaro** [comment]
Added in 1.20.1-1.1.1, 1.20.2-1.0.4, and 1.20.4-1.0, thanks for requesting.
Note: To add this specific compatibility, you can add the id of this fluid in the BFR server config, in "upgrade.additional_liquid_fuels" list. (You need ForgeConfigAPI in Fabric)
