### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by Meneghiin** [Wilyicaro/BetterFurnacesReforged#151]
### Better Furnaces Reforged Version

1.19.4

### Mod Loader Version

Forge 45.2.6

### Bug/Glitch Occurrence Context

Unable to create furnaces.
![2024-01-31_20 04 28](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/158371115/eb5a697d-c8d5-4362-8ffd-9a76836c164b)

### What happened wrong?

![2024-01-31_20 04 28](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/158371115/eb5a697d-c8d5-4362-8ffd-9a76836c164b)

**Comment by Wilyicaro** [comment]
![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/81383021/db1ac7d6-a0ac-45c4-b507-3ae1ecc74612)

Probably, this is some incompatibility, as I've never had this problem with recipes.
