### ISSUE TITLE
[Bug/Glitch] (Crash Error)

### ISSUE THREAD

**Issue by LeviathanSS** [Wilyicaro/BetterFurnacesReforged#152]
### Better Furnaces Reforged Version

1.20.2

### Mod Loader Version

Fabric Loader 0.15.6

### Bug/Glitch Occurrence Context

Whenever its right clicked.

### What happened wrong?

Whenever I right click any Better Furnaces Reforged furnace, it freezes and crashes the game.

**Comment by Wilyicaro** [comment]
Probably, this is an incompatibility with some mod, as BFR Fabric 1.20.2-1.0.3 is working normally for me, you should send the crash report, so I can fix it.

**Comment by LeviathanSS** [comment]
> Probably, this is an incompatibility with some mod, as BFR Fabric 1.20.2-1.0.3 is working normally for me, you should send the crash report, so I can fix it.

Here is the crash log:
[latest.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/14144487/latest.log)

**Comment by Wilyicaro** [comment]
Install Factory API 2.0.1 for now, this is a known issue with the last version, it will be fixed in the next version

**Comment by FrozenGalaxy** [comment]
Still happens on the newest version btw https://gist.github.com/FrozenGalaxy/9370caa8aa9849a83493892233c03ab7

> it will be fixed in the next version

Is that out yet?

**Comment by Wilyicaro** [comment]
> Still happens on the newest version btw https://gist.github.com/FrozenGalaxy/9370caa8aa9849a83493892233c03ab7
> 
> > it will be fixed in the next version
> 
> Is that out yet?

No, this is not the same crash, the incompatibility with the newer versions of Factory API was fixed in 1.20.1-1.1.1, but this incompatibility with Rail Craft of your crash is still happening, apparently

**Comment by FrozenGalaxy** [comment]
So its still an issue with FactoryAPI tho?

**Comment by Wilyicaro** [comment]
> So its still an issue with FactoryAPI tho?

Definitely not, was fixed in BFR 1.20.1-1.1.1 as I said.

**Comment by Edivad99** [comment]
Fixed in https://github.com/railcraft-reborn/railcraft/commit/3810e3c79e68c86d72fbe237e1ceb2ae1073b79c
