### ISSUE TITLE
[Bug/Glitch] What is up with the Forge placement and rotation?

### ISSUE THREAD

**Issue by alucard87pl** [Wilyicaro/BetterFurnacesReforged#154]
### Better Furnaces Reforged Version

1.20.1-1.1.2

### Mod Loader Version

Forge 47.2.20

### Bug/Glitch Occurrence Context

I'm playing on the Ozone Skyblock Reborn modpack from curseforge.
Maybe I'm just stupid and there's a way to do this.

### What happened wrong?

I can't for the life of me figure out how to place/rotate a Diamond Forge the way I want it.
I'm verifying the placement with the piping/factory upgrade Orientation toggle.
It consistently places itself with it's RIGHT face facing me (I'd expect Front). It also sometimes places sideways or upside down, no matter which side/edge of a block I'm looking at when placing. Using the Crescent Hammer from Thermal doesn't follow any pattern I've tried.
Also, It doesn't seem to appreciate EnderIO's Item conduits, even when I verified and confirmed I'm pushing items into the correctly set slots.

**Comment by alucard87pl** [comment]
Okay, now I am lost, completely.
![2024-02-13_12 13 15](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/7818225/52f1042a-4ae5-4895-8f13-6015c51d69a7)
Piping in the Front face (one would assume, as it's on the other side of the block as the Back face)
But the config says otherwise:
![2024-02-13_12 15 00](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/7818225/313ff2cf-1612-414e-92b3-5a9fdfdf99b4)

**Comment by Wilyicaro** [comment]
Firstly, about the forge placement, simply it's like a log, as I said in #55 and #34, and obviously it's not like a furnace, because it has a radial symmetry.
And as for the back and front config, it's a bug, they're swapped, it'll be fixed in version 1.20.1-1.1.3
