### ISSUE TITLE
version incompatibility error

### ISSUE THREAD

**Issue by Rogenar** [Wilyicaro/BetterFurnacesReforged#155]
### Better Furnaces Reforged Version

BetterFurnaces-1.20.4-1.0.1-fabric

Factory API [Fabric] 1.20.4-2.1

### Mod Loader Version

0.15.7

### Bug/Glitch Occurrence Context

![sss3](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/122460325/612c9dca-6a8e-481d-9a9c-fe03dbbef747)
[latest.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/14374453/latest.log)
I encounter this error when starting the game.

### Crash Report

sss3

### What happened wrong?

undefined

**Comment by Wilyicaro** [comment]
Fixed in version 1.20.4-1.0.2
