### ISSUE TITLE
Relog deletes furnace inventory

### ISSUE THREAD

**Issue by Crowvas** [Wilyicaro/BetterFurnacesReforged#16]
Mod Version-Minecraft Version
Forge Version **1.18**
Mod Version **1.18**

Bug/Glitch Occurrence Context
**Doesn't Crash. Works fine, almost.**

What happened wrong
**Relogging into game using any upgraded forge clears its inventory of fuel, upgrades, material to be refined and refined material**

**Comment by Wilyicaro** [comment]
Honestly, I don't even know what's going on, with forge normally installed on minecraft, really this bug actually occurs, but when I test on IntelliJ, the inventory is saved normally

**Comment by Wilyicaro** [comment]
Fixed in 1.18.1-1.0.2

**Comment by Wilyicaro** [comment]
Thank you very much for reporting the serious bug
