### ISSUE TITLE
[Bug/Glitch] Ore Processing Upgrade/Advanced Ore Processing Upgrade Not Doubling Ore Output Correctly

### ISSUE THREAD

**Issue by RDTurcios** [Wilyicaro/BetterFurnacesReforged#160]
### Better Furnaces Reforged Version

1.20.4

### Mod Loader Version

Fabric Loader 0.15.10

### Bug/Glitch Occurrence Context

I put the upgrade in the designated slot, and it doesn't double the ore output (or any output). However, it does double the Cobblestone Generator output. This also applies to the regular ore processing upgrade.

### What happened wrong?

Raw ores don't get doubled, but the ore (e.g., Gold Ore) does.

https://github.com/Wilyicaro/BetterFurnacesReforged/assets/63935190/a79c05dc-13f7-4f2d-bb09-c43ac4d54129

https://github.com/Wilyicaro/BetterFurnacesReforged/assets/63935190/55c1e1b2-f5c7-4b93-a172-081903e89eee

**Comment by Wilyicaro** [comment]
As you can see, there is an upgrade called Raw Ore Processing Upgrade precisely for raw ores, this was already mentioned in #18.

**Comment by RDTurcios** [comment]
Thanks, didn't realize that was a thing in the mod. That being said, the crafting recipe is really expensive. Is there a way to change the crafting recipe or make it a bit simpler to obtain? Just a suggestion.
