### ISSUE TITLE
Shift+LeftMouseClick BUG

### ISSUE THREAD

**Issue by awe74** [Wilyicaro/BetterFurnacesReforged#17]
Hi!

I have found a BUG, on Fuel Power Verifier. Shit+LeftMouseClick on any item in the inventory is duplicate it.
Here is a link, for video: [https://mega.nz/file/fwJA1ZIb#OCeOSOu-Er1EExws5zv9ESPCzBgKktlWYtxOcPQPPqI](url)

**Comment by Wilyicaro** [comment]
I'll check this out sometime, it's nothing serious to fix, but I'm not currently doing mod updates, probably the fix will be released next year. Please follow the proposed template on CurseForge to post Issues to facilitate corrections
