### ISSUE TITLE
1.18.1 - Fuel Liquid Upgrade works with Creosote Oil, but not consumed it

### ISSUE THREAD

**Issue by Justus75** [Wilyicaro/BetterFurnacesReforged#19]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.0

**Mod Version:** BetterFurnacesReforged-1.18.1-1.0.2

**Single Player or Server:** Single Player

**Describe problem (what you were doing; what happened; what should have happened):**
In Diamond Furnace i use a Fuel Liquid Upgrade and a bucket of Creosote Oil (Immersive Engineering). It works very fine, but but that liquid is not consumed. 

**Log file link:** -none-

**Video/images/gifs (direct upload or link):**

<img width="404" alt="2021-12-26 21_35_38-Minecraft_ 1 18 1 - Singleplayer" src="https://user-images.githubusercontent.com/96327909/147419528-f2e05f83-8b2b-46d9-a87e-911c900fc188.png">

**Comment by Wilyicaro** [comment]
First, with the fuel liquid upgrade, you need to press the right button with the fuel bucket in the furnace to make use of this upgrade and fill the tank
Also, I certainly haven't programmed to remove the creosote oil bucket when it burn, a fix will be released soon

**Comment by Wilyicaro** [comment]
Fully fixed in version 1.16.5-1.6.2
