### ISSUE TITLE
Bug in 1.12.2

### ISSUE THREAD

**Issue by pverissimo19** [Wilyicaro/BetterFurnacesReforged#2]
I am playing in LAN with my brother and the diamond furnace doesn't work with ore processor it only burns 1 stack and then it stops I have to break the furnace and replace it otherwise it will not work
![image](https://user-images.githubusercontent.com/88854688/129255496-025858e4-dfaf-4f38-af6a-725be13193aa.png)

**Comment by Wilyicaro** [comment]
I imagine this doesn't just happen with the diamond furnace, I'll fix that soon, it's certainly not a major error in the code.

**Comment by pverissimo19** [comment]
It happen also with the netherhot furnace I am not sure if it happens with
all furnaces but at least with those two it happens

A quinta, 12/08/2021, 22:45, Wilyicaro ***@***.***> escreveu:

**Comment by Wilyicaro** [comment]
Good news! This bug has been fixed in the new version 1.3.1

Thanks for reporting it : )

**Comment by pverissimo19** [comment]
Awesome, thanks for the update!

A sexta, 13/08/2021, 12:52, Wilyicaro ***@***.***> escreveu:
