### ISSUE TITLE
[1.18.1, 1.1.1]Factory upgrade auto-input voids items

### ISSUE THREAD

**Issue by hypernova132** [Wilyicaro/BetterFurnacesReforged#21]
When I put items in a chest next to a furnace with a factory upgrade that has auto-input turned on the items just disappear from the chest and aren't put into the furnace.

**Comment by Wilyicaro** [comment]
I will look at this to be fixed in the next update.

**Comment by Wilyicaro** [comment]
Fixed in version 1.18.1-1.2
