### ISSUE TITLE
Cobblestone Generator can't return to state 0

### ISSUE THREAD

**Issue by mouse0270** [Wilyicaro/BetterFurnacesReforged#22]
**Minecraft Version:** 1.18.1
**Mod Version:** 1.1.1
**Forge Version:** 39.0.9

**What happened wrong**
The cobblestone generator has four states. The default state with no lava/water, the states with lava or water and lastly the state with both. However, if you put a bucket of lava in and remove it, the state does not change back to 0, instead it stays at state 1. The same happens with water. It appears it's impossible to get the state back to 0

**Comment by Wilyicaro** [comment]
I'll check it out, and fix it in the next version.

**Comment by Wilyicaro** [comment]
Fixed in version 1.18.1-1.2
