### ISSUE TITLE
Upgrade of advanced ore processing doesn't works

### ISSUE THREAD

**Issue by Phoenix-99** [Wilyicaro/BetterFurnacesReforged#23]
Mod Version (1.7)-Minecraft Version (1.16.5)
Forge Version (1.16.5-forge-36.2.6)

Bug/Glitch Occurrence Context
Advanced ore processing and ore processing upgrade doesn't works

What happened wrong
I installed the advanced ore processing upgrade to my furnace and when i put ores, this dont duplicate the ores

**Comment by Wilyicaro** [comment]
It has already been fixed, and will be released in the next update.
