### ISSUE TITLE
Duplicating ores without upgrade

### ISSUE THREAD

**Issue by shrad1994** [Wilyicaro/BetterFurnacesReforged#24]
So I have a hopper feeding and iron furnace, and a hopper sucking the material out of it.

Somehow it's giving me 4 bars per 1 ore with no upgrades in it. 

With some testing it only seems to be duplicating copper

**Comment by Wilyicaro** [comment]
What version of the game and mod?  The versions I am constantly updating (1.16.5 and 1.18.1) do not have this bug, because I have already corrected

**Comment by shrad1994** [comment]
It is 1.18.1 and I believe it would have been the latest version of your mod about mid to late December when I originally downloaded

**Comment by shrad1994** [comment]
I'll grab some screenshots or video once I'm off work

**Comment by Wilyicaro** [comment]
I didn't put that to fix this bug in the changelog, but I believe it was in version 1.18.1-1.2 of the mod that I fixed this bug, which was released on January 4th

**Comment by Wilyicaro** [comment]
No need to show the screenshots, just update the mod to the latest version, which already had it fixed
