### ISSUE TITLE
Crash on world start

### ISSUE THREAD

**Issue by hypernova132** [Wilyicaro/BetterFurnacesReforged#26]
[crash-2022-01-16_19.59.12-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/7878545/crash-2022-01-16_19.59.12-server.txt)

**Comment by Wilyicaro** [comment]
You probably got this crash when loading a world with an old version of the mod, right?
If so, I will fix it in the next version of the mod, but for now, as your world is "unusable", use version 1.2.1 of the mod

**Comment by Wilyicaro** [comment]
Fixed in mod version 1.18.1-1.2.3 and 1.16.5-1.7.3
