### ISSUE TITLE
No Output.

### ISSUE THREAD

**Issue by liltoby** [Wilyicaro/BetterFurnacesReforged#28]
There is no output on the furnaces so they can not be used with any other automation mods. Really upsetting as they would be great replacements furnaces for my automatic smelting system.

Forge 1.17.1

**Comment by Wilyicaro** [comment]
I had abandoned updates to 1.17.1 version as I thought no one else would use it to play with mods. I will release at least one last update, being a port of version 1.18.1, to fix this bug

**Comment by liltoby** [comment]
Thank you very much :)
