### ISSUE TITLE
Mod crashes Server

### ISSUE THREAD

**Issue by JaNOriginalDe** [Wilyicaro/BetterFurnacesReforged#3]
[crash-2021-08-14_00.20.53-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/6985412/crash-2021-08-14_00.20.53-server.txt)

**Comment by JaNOriginalDe** [comment]
At the startup

**Comment by JaNOriginalDe** [comment]
[crash-2021-08-14_10.32.39-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/6986162/crash-2021-08-14_10.32.39-server.txt)
I forgot the CXLibrary modd but it didnt fixed the issue

**Comment by Wilyicaro** [comment]
Good news! This crash has been fixed in the new version 1.3.2

Thanks for reporting it : )
