### ISSUE TITLE
Cobblestone generator crashed the game

### ISSUE THREAD

**Issue by Mirko166** [Wilyicaro/BetterFurnacesReforged#30]
Mod version: 1.7.3
Forge version: 1.16.5-Forge-36.2.20
Minecraft version: 1.16.5

What happened wrong:
My game crashes when I interact with the cobblestone generator

Crash report:
[crash-2022-03-22_12.56.28-client.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/8324030/crash-2022-03-22_12.56.28-client.txt)

**Comment by Wilyicaro** [comment]
Could you also specify what you did to make this bug occur, like the upgrades you put in the cobblestone generator, the generation mode you put. If this crash simply occurred when placing the block and opening the interface, I believe it is some incompatibility with some mod in your modpack, as everything works normally in version 1.16.5-1.7.3

**Comment by Mirko166** [comment]
the game only crashes when i interact with the cobblestone generator, no
matter if there are upgrades in it or not. also i tested in a singleplayer
world and the game does not crash but it only happens when i play in a
server, regardless of the other mods

Il Mer 23 Mar 2022, 06:14 Wilyicaro ***@***.***> ha scritto:

**Comment by Wilyicaro** [comment]
I already fixed this bug in the latest mod version of 1.16.5 and 1.18.2 which I didn't release on Curseforge, it was a simple bug, thank you very much for reporting.

**Comment by Mirko166** [comment]
Thanks for the information. But at this point the problem is that the
latest version for 1.16.5 not being on curseforge makes it impossible for
me to download it on the aternos site server. Are you planning to add this
fix to curseforge?

Il Mer 23 Mar 2022, 22:43 Wilyicaro ***@***.***> ha scritto:

**Comment by Wilyicaro** [comment]
There's no way to download the jar on Github anyway, but I'm making some more changes to the cobblestone generator before posting this update on CurseForge.  Until tomorrow I think I can post

**Comment by Mirko166** [comment]
Ok, Thanks so much for your help :)

Il Gio 24 Mar 2022, 11:06 Wilyicaro ***@***.***> ha scritto:
