### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Mirko166** [Wilyicaro/BetterFurnacesReforged#31]
Mod version: 1.8
Minecraft version: 1.16.5
Forge version: 1.16.5-forge-36.2.20

What happened wrong:

After the 1.8 update i can't enter in my aternos server, instead i get an error screen. I also tried to open the server only with this mod but it still give me the same error

![Minecraft error](https://user-images.githubusercontent.com/102156677/160652584-3adeb4e8-5ab7-4221-8d51-712211f01d7f.png)

**Comment by Wilyicaro** [comment]
Fixed in 1.16.5-1.8.1 and 1.18.2=1.1.1 version

**Comment by Mirko166** [comment]
Thanks!

Il Gio 31 Mar 2022, 05:28 Wilyicaro ***@***.***> ha scritto:
