### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by xuexiyue** [Wilyicaro/BetterFurnacesReforged#32]
Missing texture for all the forges from the addon mod Ultimate furnaces BFR addon, they show as black and blue/purple?(sorry I'm color blind) boxes.

**Comment by Wilyicaro** [comment]
The ultimate furnaces addon is not updated with the latest features of the base mod, this error is only visual and can be solved with a resource pack, for now I am not able to make changes to the mod.  Ah, it's your color blindness, Minecraft's missing texture colors are purple and black ;)
