### ISSUE TITLE
Client crash when opening cobblestone generator

### ISSUE THREAD

**Issue by Neurosis404** [Wilyicaro/BetterFurnacesReforged#33]
Minecraft version: 
1.18.2

Forge version: 
40.1.16

Java version: 
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

Crash repot: 
https://pastebin.com/FKf2sUnt

What happened? 
Client chrashes upon opening the GUI of the cobblestone generator. The generator is set to "Obsidian". It worked before, the issue started at some point

**Comment by Wilyicaro** [comment]
Thanks for the report, it will be fixed in 1.18.2-1.2.1
