### ISSUE TITLE
Orientation of extreme forge incorrect

### ISSUE THREAD

**Issue by Staegrin** [Wilyicaro/BetterFurnacesReforged#34]
version :BetterFurnacesReforged-1.18.2-1.2
Forge 40.1.47
When placing an Extreme Forge the top of the block orients towards the player instead of the front of the Forge facing the player
![2022-06-12_01 48 05](https://user-images.githubusercontent.com/8494635/173208499-29b23e6a-cb98-4a8a-afde-17bf45c4da56.png)
![2022-06-12_01 48 01](https://user-images.githubusercontent.com/8494635/173208501-8c728ce4-f2cc-49db-87f5-55113c7374b1.png)
.

**Comment by Wilyicaro** [comment]
I don't see a problem with that, the orientation was programmed that way, to be the opposite of the player's orientation, and the normal for the forge is the north state, which has the top side oriented up and the front facing towards the player, think of it as a log of wood
