### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [Wilyicaro/BetterFurnacesReforged#35]
https://paste.ee/p/UvvUo

**Comment by Wilyicaro** [comment]
It's probably an incompatibility of the Quark mod in 1.12.2 with BetterFurnaces Reforged, I believe you should try removing BFR and/or Quark, but from what I could see in the crash report it has nothing directly to do with the BFR classes

**Comment by Wilyicaro** [comment]
Fixed in 1.12.2-1.5.2,, thanks for reporting this crash.
