### ISSUE TITLE
Lose buckets

### ISSUE THREAD

**Issue by CosminSA** [Wilyicaro/BetterFurnacesReforged#36]
In version 1.18.2 if I put a factory update, with auto input output, and put multiple buckets of lava in the fuel chest, after using them only one remains empty, the rest are deleted

**Comment by Wilyicaro** [comment]
First, use Fuel Liquid Upgrades if the furnace/forge have upgrade slot available, much better than putting too many buckets of lava in a chest with Factory Upgrade. 
And thanks for reporting this bug, I would never think of this situation, I will fix it as soon as possible

**Comment by Wilyicaro** [comment]
If you can, send the mod version in 1.18.2 and a video with it happening, because I tried to reproduce what you did and it simply consumed only 1 bucket

**Comment by CosminSA** [comment]
[video.zip](https://github.com/Wilyicaro/BetterFurnacesReforged/files/8936139/video.zip)
[mods.zip](https://github.com/Wilyicaro/BetterFurnacesReforged/files/8936140/mods.zip)
it's the same without liquid upgrade, but the video was too big to upload on github
forge version 1.18.2-forge-40.1.0

**Comment by Wilyicaro** [comment]
Fixed in 1.18.2-1.2.2, and again, thanks for reporting this bug
