### ISSUE TITLE
Server crashes on furnace opening (Diamond only tested)

### ISSUE THREAD

**Issue by JaNOriginalDe** [Wilyicaro/BetterFurnacesReforged#4]
[crash-2021-08-15_10.28.10-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/6987773/crash-2021-08-15_10.28.10-server.txt)

**Comment by JaNOriginalDe** [comment]
This only happened after placing the furnace the first time. After the crash it sort of worked.

**Comment by JaNOriginalDe** [comment]
After I left the area so it is unloaded it also crashes the server afte
[crash-2021-08-15_10.39.08-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/6987793/crash-2021-08-15_10.39.08-server.txt)
r loading that chunk again. With the same issue.

**Comment by Wilyicaro** [comment]
First of all, thanks for reporting this serious bug!  I will soon get more information about this crash, and fix it.

**Comment by Wilyicaro** [comment]
This bug was officially fixed in version  rrelease 1.12.2-1.4, I should have tested several scenarios before publishing this mod version, sorry for the inconvenience
