### ISSUE TITLE
Cobblestone generator crash

### ISSUE THREAD

**Issue by SonicGleb** [Wilyicaro/BetterFurnacesReforged#41]
Minecraft Version: 1.16.5
Forge version: 36.2.35
Mod Version: 1.16.5-1.9.1f

On the server (and in singleplayer) after placing cobblestone generator and opening it on the second time and more, the game will crash. With NotEnoughCrashes mod after rejoining the world no entities being rendered, so you have to restart the game anyway.

[crash-2022-06-27_20.21.29-client.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/8994697/crash-2022-06-27_20.21.29-client.txt)

**Comment by Wilyicaro** [comment]
Fixed in 1.16.5-1.9.2 version
