### ISSUE TITLE
Cobblestone Generator doesn't work (1.19 forge 41.0.63)

### ISSUE THREAD

**Issue by DragonEater2008** [Wilyicaro/BetterFurnacesReforged#45]
in my survival world, the cobblestone generator doesn't work whatsoever. I tried reloading the world, activating cheats with an external program, changing my game mode to creative and turning cheats off. none of those work. the generator only wworks in my other world that was in creative when i created the world.

**Comment by DragonEater2008** [comment]
Nvm it works

**Comment by Wilyicaro** [comment]
There is no way to have a difference in the functioning of the block if it is in the creative or not, check if there is no redstone signal nearby, because the cobblestone generator is turned off if there is any redstone signal
