### ISSUE TITLE
la mejora de liquido (fuel liquid upgrade) no transporta la lava (v1.16.5 MC | 1.9.4 BFR)

### ISSUE THREAD

**Issue by Lenis-Felipe** [Wilyicaro/BetterFurnacesReforged#47]
hola, tengo minecraft tlauncher donde he instalado y juego la 1.16.5 ForgeOptifine, descargué el mod BFR para la versión correspondiente, 1.9.4 para la 1.16.5, el problema que tengo es que la mejora de liquido NO lleva la lava, más bien es como la llave para acceder a un tanque de lava que tiene un horno, es obvio que sin el item, no puedes cocinar con lava, pero hay un error, cuando saco el item de un horno y se lo pongo a otro la lava no aparece, pero si lo devuelvo, la lava aparece
para que entiendan mejor, puse un video para que lo vean
https://user-images.githubusercontent.com/93104242/180624963-bedc647b-1e98-4cf6-bb70-a55467e6a67b.mp4

**Comment by Wilyicaro** [comment]
First, this is not "ridiculous", have you ever seen a mod that has a "fluid tank upgrade" with a simple recipe and that still saves the liquid placed in the block in the item itself?

**Comment by Wilyicaro** [comment]
Y además, no insultes a ningún mod o creador, eso es ridículo. Estos insultos pueden hacer que tu denuncia sea ignorada por tu mala educación

**Comment by Lenis-Felipe** [comment]
solo quiero que el mod tenga mas sentido, pido disculpas si me pasé, pero quiero que el mod sea mas realista
