### ISSUE TITLE
ERROR HACE QUE EL MUNDO SELECCIONADO SEA INACCESIBLE

### ISSUE THREAD

**Issue by Lenis-Felipe** [Wilyicaro/BetterFurnacesReforged#48]
anteriormente he publicado un problema pequeño que tuve aquí: https://github.com/Wilyicaro/BetterFurnacesReforged/issues/47, pero esta vez me ha pasado uno grave, intenté volver a hacer el mismo error, pero no ha salido, tuve un error con el generador de rocas, cuando cambié la opcion que tipo de roca quería obtener, el juego me sacó, y cuando quise volver a entrar, nuevamente me sacó, por lo que tuve que borrar el mundo, menos mal que apenas había empezado en modo creativo, porque imagínensen si ustedes estuvieran en supervivencia, después de horas y horas de buscar por fin consiguieron materiales para no solo hacer el generador de rocas, sino tambíen para hacer el horno extremo, mejoras y otras cosas, y resulta que de un momento a otro, cuando ustedes quieren ir al nether facil usando un balde con agua y otro con lava para hacer obsidiana con el generador, SE CRASHEA, estás preocupado porque te sacó el juego sin tu consentimiento, y quieres volver a entrar como me pasó a mí, y no deja, ASI ES, pierdes TODO lo que conseguiste,
Wilyicaro, ¿Puedes revisar todos las acciones de los hornos, generadores, etc. para encontrar si hay un error?, y si lo hay, ¿almenos publiques la 1.9.5 para la 1.16.5 con los bugs y glitches reparados por favor? gracias

**Comment by Wilyicaro** [comment]
Look, you don't need to write this kind of thing in capslock, if it was such a frequent and serious bug, why didn't anyone report it anymore?  Also, descriptions don't help to solve a crash, but the crash report does.

**Comment by Lenis-Felipe** [comment]
al menos puedes publicar la 1.9.5 con el bug liquid fuel upgrade solucionado?

**Comment by Wilyicaro** [comment]
This is not a bug, it's simply a feature that I don't want to add to the mod, because it makes the gameplay easier and isn't present in the original 1.7.10 mod

**Comment by Wilyicaro** [comment]
And yes, I will post version 1.9.5, with parity with version 1.18.2-1.2.7 and 1.19-1.0.6
