### ISSUE TITLE
recipes not popping up

### ISSUE THREAD

**Issue by Shellingwag** [Wilyicaro/BetterFurnacesReforged#5]
Hello I'm using the 1.16.5-1.2 version and I wanted to try out the mod in game. for some reason the recipes for the better furnaces don't pop up on their own. The items are in game, but I can only access them either through creative or by using the recipes posted on curseforge. Is it a coding issue or am I just missing something?

**Comment by Wilyicaro** [comment]
Very strange this bug, I always do several tests before posting these new versions on curseforge, I'll check it and soon I'll answer

**Comment by Wilyicaro** [comment]
Ah, now I understand your question, the recipe book does not show mod recipes correctly, I recommend using the JEI (Just Enough Items)
