### ISSUE TITLE
Infinite Fuel Glitch

### ISSUE THREAD

**Issue by TC1010tiago** [Wilyicaro/BetterFurnacesReforged#50]
**Versions**
BetterFurnacesReforged-1.19-1.0.6 - Minecraft ForgeOptiFine 1.19 (TLauncher)
Forge-1.19-41.1.0

**Details**
I recently started hosting a forge server so that I could play with my friends. I have about 20 mods loaded and everything is working fine except for a small detail which is not inconvenient but I assume it's not supposed to work like that.
Every furnace from the BetterFurnacesReforged mod is not consuming any kind of fuel, it's working as if the fuel was infinite without having the infinite fuel upgrade.

**Mods**
![mods](https://user-images.githubusercontent.com/110487725/182437657-c91368ba-f181-4dd5-bbd8-5b210ca6a11f.png)

**Comment by Wilyicaro** [comment]
Hello, thanks for reporting this problem, I will check it as soon as possible, it's just a detail that the mod doesn't have any "infinity fuel upgrade"

**Comment by Wilyicaro** [comment]
Fixed in 1.19.1-1.0

**Comment by TC1010tiago** [comment]
Obrigado! Espero ter ajudado!
