### ISSUE TITLE
Not burning Fuel

### ISSUE THREAD

**Issue by wildkurt** [Wilyicaro/BetterFurnacesReforged#51]
Minecraft version: 1.19
Better Furnaces Reforged version: 1.19-1.0.6
Forge: 41.1.0

I have been putting kelp blocks in the mod furnaces and while they are cooking things, they aren't using any fuel. I haven't tried with coal, but my setup is based on kelp blocks.

**Comment by Wilyicaro** [comment]
Sorry for the inconvenience, but this bug has already been solved in version 1.19.1-1.0 of the mod, if possible update your minecraft and forge to the newest version. 
It's not very practical for me to work with several minecraft subversions, because the changes are mostly very small

**Comment by wildkurt** [comment]
No problem was just hoping to be of help. I like this mod a lot. Really glad you ported it to 1.19.
