### ISSUE TITLE
Duplicating Items

### ISSUE THREAD

**Issue by Junior-Winchester** [Wilyicaro/BetterFurnacesReforged#52]
Putting any stackable item in a specific slot in the inventory and then pressing shift + left button duplicates the item, watch the video: https://www.youtube.com/watch?v=xgoK69hjue8 

Apparently, this bug can be done in any furnace of the mod.

Version: 1.19.1

**Comment by Wilyicaro** [comment]
Thanks for reporting this bug, soon I will fix it

**Comment by Wilyicaro** [comment]
Fixed in 1.19.2-1.0.1,  1.16.5 and 1.18.2 soon
