### ISSUE TITLE
[1.16.5] CRASH When using furnaces from Ultimate BFR Addon

### ISSUE THREAD

**Issue by Cynix32** [Wilyicaro/BetterFurnacesReforged#53]
1.16.5
Forge 36.2.39
BetterFurnacesReforged-1.16.5-1.9.7.jar
Ultimate-Furnaces-BFR-1.16.5-1.3.1.jar

How:
1. Load up a world
2. Place an Ultimate Furnace or an Ultimate Forge (both will make it crash)
3. Right Click on the furnace to use it
4. CRASH

CRASHLOG: https://pastebin.com/ZCzsm5E8

**Comment by Wilyicaro** [comment]
The Ultimate Furnaces addon does not yet have total compatibility with versions of Better Furnaces Reforged after the date of its release, it will soon be updated to add this support

**Comment by Wilyicaro** [comment]
For now, don't use this addon, if you're using it in survival mode, avoid it until the update

**Comment by Cynix32** [comment]
oof, i was actually pretty far into my survival run the moment I discovered this crash, Thankfully this crash isn't world-breaking.

**Comment by Wilyicaro** [comment]
Fixed in Ultimate Furnaces 1.19.2-1.0, 1.18.2-1.3 and 1.16.5-1.3.2
