### ISSUE TITLE
Ultimate Furnaces crashes

### ISSUE THREAD

**Issue by Dr-WeiAL** [Wilyicaro/BetterFurnacesReforged#54]
Version: 1.18.2
Better Furnaces Reforged Version: 1.2.9
Ultimate Furnaces: 1.0.1

Opening any of the Ultimate Furnaces GUI will crash the game
[crash-2022-09-12_23.37.33-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/9549564/crash-2022-09-12_23.37.33-server.txt)

**Comment by Wilyicaro** [comment]
#53 Duplicated
