### ISSUE TITLE
Forge texture bug

### ISSUE THREAD

**Issue by Dr-WeiAL** [Wilyicaro/BetterFurnacesReforged#55]
![image](https://user-images.githubusercontent.com/47446553/190042173-728f4144-6950-4107-8df8-9afe4f7ab490.png)
The forge will be turned upside down when placed a little further away

By the way, the furnace needs very high temperatures to work, so it shouldn't have too many working windows exposed to air, so it's better to have only one side instead of four?

**Comment by Wilyicaro** [comment]
First of all, the forge's orientation is always the opposite of the orientation you are in at the time you place it, this is a way of making it a decorative block as well.  
And about finding logic in a minecraft mod, Better Furnaces Reforged forges are made to be compact forges, and feature 4 "windows" to represent that they hold more items than a regular furnace(symmetry also), and even with these air vents, does not cool the forge, as it can efficiently get enough temperature to smelt items.
