### ISSUE TITLE
Project MMO 1.19 Compat Request

### ISSUE THREAD

**Issue by Caltinor** [Wilyicaro/BetterFurnacesReforged#57]
Good Day,

I am the new maintainer of PMMO.  Compat with your mod is one of the highest requested features.  As you noticed, PMMO went into an alpha state in 1.18.  This was due to a complete rewrite of the mod.  Part of that included a redesign of how smelting compat was implemented.   For clarification, this request does not apply to the 1.18 alpha, but only to the 1.19 release version.

In the 1.18 (alphas) and 1.19 (release) PMMO now provides an event which can be posted to the Forge Event Bus.  [event code reference](https://github.com/Caltinor/Project-MMO-2.0/blob/main/src/main/java/harmonised/pmmo/api/events/FurnaceBurnEvent.java).  this is a non-cancellable event, and simply adds more context than the Forge-provided smelt event does which PMMO needs for ownership identification.  Compat with PMMO should be as simple as `MinecraftForge.EVENT_BUS.post(new FurnaceBurnEvent(outputStack, blockEntityLevel, blockEntityBlockPos));` when the output is generated.

I am happy to provide this as a PR, if that is your preference.  The code for your blockentities is rather robust, though.  So this approach seemed faster than what it would take for me to study then implement.

**Comment by Wilyicaro** [comment]
Sorry for the late reply, but thank you very much for clarifying the implementation of these new Project MMO events for Forge Event Bus. Soon I will implement it in version 1.19.2 of BFR

**Comment by Wilyicaro** [comment]
Fixed in 1.19.2-1.0.2 version
