### ISSUE TITLE
Liquid Fuel Upgrade not working.

### ISSUE THREAD

**Issue by ramirez-luis** [Wilyicaro/BetterFurnacesReforged#6]
I'm using BetterFurnaces Reforged 1.12.2 1.4 and the liquid fuel upgrade doesn't work. I can't use lava buckets as fuel. In fact, I can't use any fuel while the upgrade is in the furnace. Is this normal behavior? Is it different from previous versions of the mod (I mean before "Reforged")?

**Comment by Wilyicaro** [comment]
Unlike the original mod, to put combustible liquids (lava) in the furnace with Liquid Fuel Upgrade, just right click with the bucket in the furnace, or use tubes to transport liquids to it

**Comment by Wilyicaro** [comment]
Maybe I'll put it to be able to put lava directly on the furnace interface

**Comment by Wilyicaro** [comment]
Note: this is a feature that I added exclusively in this version, the 1.16 version works the same as the classic version (1.7.10)

**Comment by ramirez-luis** [comment]
Oh, okay. Thanks, and sorry to bother you!

I didn't try to right click because I was afraid to burn down my house by accident lol.
