### ISSUE TITLE
using an energy upgrade causes the game to crash and the world to be unacessible

### ISSUE THREAD

**Issue by superforgamer** [Wilyicaro/BetterFurnacesReforged#61]
BetterFurnacesReforged-1.12.2-1.5.3 - 1.12.2
forge 14.23.5.2860

context: using an ender io conduit to put power on an extreme forge with the energy upgrade, same happens with thermal expansion fluxducts.

when trying to use an energy upgrade on the extreme forge the game crashes and continues to crash whenever i go back to the world.

plataform is linux_X86 with the 5.15.0-48-generic kernel on a mate de if that helps with anything

crash log:
[crash log better frunaces.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/9848725/crash.log.better.frunaces.txt)

**Comment by Wilyicaro** [comment]
It's certainly not a bug related to Ender IO, from looking at the crash report I can't say that yet, but what is certain is fuel burning related.  I guarantee I'll fix the bug soon

**Comment by Wilyicaro** [comment]
Fixed in 1.12.2-1.5.4
