### ISSUE TITLE
Crash With Entangled 1.19.2

### ISSUE THREAD

**Issue by Cyranos** [Wilyicaro/BetterFurnacesReforged#62]
The game crashes when trying to hook up any furnace from this mod to an entangled block.
Minecraft Version; 1.19.2
Forge Version; 43.1.52
Better Furnaces Reforged Version; 1.19.2-1.0.3
Entangled Version; 1.3.11.b

Crash Log;
https://mclo.gs/dOselV6

**Comment by Wilyicaro** [comment]
Apparently it's a simple bug related to Color Upgrade, thanks for reporting it and introducing me to this mod which looks very useful.  I'm reworking the mod completely, so I ask for patience to fix this crash

**Comment by Wilyicaro** [comment]
Fixed in 1.19.2-0.1.0 version
