### ISSUE TITLE
PMMO Parity Update [1.18.2/1.19]

### ISSUE THREAD

**Issue by OhHeyItsK** [Wilyicaro/BetterFurnacesReforged#63]
PMMOs official 1.18.2 version has been fully released and now matches 1.19, so the same update that was previously applied to 1.19 should now be applicable to 1.18.2. Just informing you for the most part, in case it's a simple fix at this point and you don't mind updating it.

**Comment by Wilyicaro** [comment]
Thanks so much for letting me know, I will add this support for 1.18.2 when I update this version
