### ISSUE TITLE
query about mod version 1.16.5 (Ultimate Furnaces)

### ISSUE THREAD

**Issue by Patatoso3** [Wilyicaro/BetterFurnacesReforged#66]
Hi! How are you?

I have a question about the mod. What mod do you recommend for the amethyst, copper, platinum furnaces? I haven't found any mods and I wanted to use them in my world. I hope not to bother!

**Comment by Wilyicaro** [comment]
Hello, I'm fine, and you?
You can simply use in version 1.16.5 the official 
Ultimate Furnaces addon in curse forge https://www.curseforge.com/minecraft/mc-mods/ultimate-furnaces-bfr

**Comment by Patatoso3** [comment]
Oh yes, i have the ultímate furnaces but i cant craft that furnaces. Which mod do you recomended to craft them?

**Comment by Wilyicaro** [comment]
Ah, now I understand you well, you can use Mekanism or/and Silent Gear with some addons like Silent Mechanisms and Silent Gems
