### ISSUE TITLE
Crash With Factory Upgrade [1.16.5]

### ISSUE THREAD

**Issue by MathisSkate** [Wilyicaro/BetterFurnacesReforged#67]
Hello i have this bug when i add the factory upgrade

Here is my crashy logs

https://crashy.net/P0oX8vdEvu8AcYLJw4Qf

**Comment by MathisSkate** [comment]
I found an other bug with Ore doubling upgrade

https://crashy.net/WHYKpqkGJzVGoVhJvLv0

**Comment by Wilyicaro** [comment]
Fixed in version 1.16.5-2.0, please open separate issues when reporting
