### ISSUE TITLE
Dupplication Glitch with Ore Processing Upgrade

### ISSUE THREAD

**Issue by MathisSkate** [Wilyicaro/BetterFurnacesReforged#68]

**Comment by Wilyicaro** [comment]
This is simply impossible, only ores, tagged forge:ores, can be duplicated by being burned, at least if these ore powders from other mods are incorrectly tagged

**Comment by MathisSkate** [comment]
I see the tags but there is only the dust tag not the forge ores

**Comment by MathisSkate** [comment]
I use all the ores

**Comment by MathisSkate** [comment]
protected boolean isOre(ItemStack input) {
        return (input.getItem().is(ore) || input.getItem().getRegistryName().toString().contains("ore"));
    }
    
    Its here in the AbstractSmetingTile class you check the registry names but alltheores as this string (ore) 
    Is that

**Comment by MathisSkate** [comment]
I checked with AllTheOres, TwilightForest, IndustrialForegoing all smelted items are doubling because of input.getItem().getRegistryName().toString().contains("ore")

the modid contains ore (f'ore'going, f'ore'st, allthe'ore's) that mean all smelted item are doubling

**Comment by Wilyicaro** [comment]
Ah, thanks for demonstrating this inconsistency, I had forgotten that I used this method at a time when the tags didn't work correctly in 1.16.5 version. I will fix it in the actual released version

**Comment by Wilyicaro** [comment]
That's what happens when you manage different versions at the same time lol

**Comment by MathisSkate** [comment]
No problem !

See yah
