### ISSUE TITLE
Liquid Fluid Update doesn't support other mods' fluids

### ISSUE THREAD

**Issue by mczph** [Wilyicaro/BetterFurnacesReforged#71]
![image](https://user-images.githubusercontent.com/103164772/211464303-31c10568-39e5-44c2-9831-26f8d8b6551a.png)
Only lava is accepted.
![image](https://user-images.githubusercontent.com/103164772/211464723-aab2a27d-bf75-4dbb-ba6d-0c7ef92ab747.png)
![image](https://user-images.githubusercontent.com/103164772/211464784-947421fe-53de-4aa3-8193-eb9f49101c62.png)

**Comment by mczph** [comment]
Maybe we should add a config for users to add their liquid fluid.

**Comment by Wilyicaro** [comment]
What version of the mod are you using? There was supposed to be this support, before the fluids of other mods were added manually in the settings in version 1.12.2, maybe there was a bug

**Comment by Wilyicaro** [comment]
Any bucket of fluid that has the ability to burn items in the vanilla furnace can be used in the Liquid Fuel Upgrade, not just lava.

**Comment by mczph** [comment]
1.12.2

**Comment by Wilyicaro** [comment]
Please also inform the list of mods, as I only tested with Creosote Oil from Thermal Expansion, it is not even considered a vanilla furnace fuel...

**Comment by Wilyicaro** [comment]
Fixed in 1.12.2-1.5.5.
This was a bug exclusive to fluids with lower burn time, such as Creosote Oil, which was not foreseen by me, and ended up generating a conflict with the higher tier furnaces of the mod
