### ISSUE TITLE
[crash] crash on load.

### ISSUE THREAD

**Issue by BamsTheSergal** [Wilyicaro/BetterFurnacesReforged#72]
https://mclo.gs/Cr4nrqw
^ logs.

refuses to launch no matter what i do. only crashes with this mod installed.

**Comment by Wilyicaro** [comment]
This crash is very strange, it did not occur in my tests on Prism Launcher itself, it is related to the Fabric API.  This could probably be some change that was made as the API updates, I will test it in current versions to see if this remains

**Comment by Wilyicaro** [comment]
Well, I tested it under the same conditions as you, but obviously without all the mods you used, and it worked perfectly.

Where did you download the mod? I did another test, and apparently the version of the mod available on Mod Rinth has this problem, I will fix it

**Comment by BamsTheSergal** [comment]
yes, i downloaded it from prism from modrinth, and i think it might just be a minor or major incompat with the new version of fabric or whatever mod i have aswell, i used packwiz to add it to a pack i am working on and it failed there too.

**Comment by Wilyicaro** [comment]
In reality it's just a bug in the version I sent to Mod Rinth, almost certainly if you get the mod from Curse Forge it will work perfectly

**Comment by BamsTheSergal** [comment]
ahh, that makes alot more sense, lol
