### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aurytis11** [Wilyicaro/BetterFurnacesReforged#76]
0.1.1-1.19.2
Fabric loader version 0.14.14

Bug/Glitch Occurrence Context
Happened in only one of my worlds but when I went to test the thing that caused my game to crash in a new world, it didn't crash. Also the thing was the ultimate forge when I put in a factory upgrade which I then quickly took out. And i know that it could be because i used an older version. And i should also add that after the crash i couldn't enter the world afterwards.
[crash-2023-02-14_13.11.33-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/10732468/crash-2023-02-14_13.11.33-server.txt)

What happened wrong
It crashed and i don't know why

**Comment by Wilyicaro** [comment]
As you said, this bug has already been fixed from 1.19.3-1.0.  I will port 1.19.3 to 1.19.2, given the large number of players that still use it, it may take a while because I lost the source code of this version due to my mistake
