### ISSUE TITLE
1.12.2   The iron furnace is not working

### ISSUE THREAD

**Issue by FanRenLa** [Wilyicaro/BetterFurnacesReforged#77]
![image](https://user-images.githubusercontent.com/83486178/219947662-4fec1e3c-650e-466c-b07e-3a7461578362.png)

**Comment by Wilyicaro** [comment]
Fixed in 1.12.2-1.5.5 patch

**Comment by Darkissou** [comment]
Same issue in 1.12.2-1.5.5
