### ISSUE TITLE
BFR Forge 1.19.2-0.2.0

### ISSUE THREAD

**Issue by Ceonci** [Wilyicaro/BetterFurnacesReforged#78]
My game just crash on load with error code 1.
Using BetterFurnaces Reforged 1.19.2-0.1.0.3 works just fine.

**Comment by Wilyicaro** [comment]
Are you using the required dependencies?

**Comment by Wilyicaro** [comment]
And also use the CurseForge page report template for support/fix be faster

**Comment by Ceonci** [comment]
Yeah, I'm using all the dependencies, Architectury API and Factory API.

Mod Version-Minecraft Version
Forge-1.19.2-0.2.0

What happened wrong
The game crash on load with exit code 1

**Comment by Wilyicaro** [comment]
What about the version of the architectury API and Factory API?

**Comment by Ceonci** [comment]
Architectury API
6.5.69

Factory API
1.19.2-0.1.6.1

**Comment by Wilyicaro** [comment]
Well, the last thing I have to know is the Forge version, otherwise everything is correct, but this error does not occur to me in the same situation

**Comment by Ceonci** [comment]
My forge version is 43.2.4

**Comment by Wilyicaro** [comment]
Please can you send the crash report?

**Comment by Ceonci** [comment]
Sadly, no crash report produced. The game crashed after clicked the play button and did not load the game. Maybe some mods compatibility issues ig.

**Comment by Wilyicaro** [comment]
> Sadly, no crash report produced. The game crashed after clicked the play button and did not load the game. Maybe some mods compatibility issues ig.


As you said, it's probably an incompatibility, if possible try running just the mod with its dependencies to see if it works normally

**Comment by Ceonci** [comment]
I tried it using just dependencies, the game still crash on launch with exit code 1 the same as before. I'm using Minecraft launcher from Windows Store with my Microsoft account,

**Comment by Wilyicaro** [comment]
I'm using Prism Launcher in my tests, but the launcher wasn't supposed to influence anything. 
If you have time, test in another launcher with multiple instances, or in a clean .minecraft

**Comment by Ceonci** [comment]
I tried using Prism Launcher with clean Minecraft. Found the culprit for it, ultimate furnaces add-on makes the game crash with better furnace forge 1.19.2-0.2.0. I can load fine when remove the ultimate furnaces add-on on Minecraft Launcher from Windows Store.

**Comment by Wilyicaro** [comment]
Ah well, the Ultimate Furnaces addon is now included in the base mod, no need to add it anymore

**Comment by Ceonci** [comment]
Oh. I see. Thank you. And sorry for the troubles.

**Comment by Wilyicaro** [comment]
You're welcome!
