### ISSUE TITLE
BFR 1.19.2-0.2.0

### ISSUE THREAD

**Issue by Ceonci** [Wilyicaro/BetterFurnacesReforged#79]
Mod Version-Minecraft Version
BFR 1.19.2-0.2.0-Forge 43.2.4-Minecraft-1.19.2

Bug/Glitch Occurrence Context
https://imgur.com/6HNYgC3

What happened wrong
Cant craft copper upgrade for furnace, got error as in the picture.

**Comment by Wilyicaro** [comment]
This recipe error will be fixed in 1.19.2-0.2.1 and 1.19.3-0.2.2
If you need this recipe for now use a datapack that replace the copper_ingot entry "tag" with "item" in data/ultimatefurnaces/recipes/copper_upgrade.json file
