### ISSUE TITLE
Crash with Applied Energistics 2

### ISSUE THREAD

**Issue by KateReller** [Wilyicaro/BetterFurnacesReforged#80]
When placing an ME Storage Bus on a Better Furnace (i.e Diamond Furnace), the game crashes.

https://mclo.gs/lEwHUfX

**Comment by Wilyicaro** [comment]
This crash will be fixed in upcoming versions 1.19.3-0.2.2 and 1.19.2-0.2.1

**Comment by Wilyicaro** [comment]
Thanks for reporting this crash!
