### ISSUE TITLE
1.19.3 My furnaces does not have any texture

### ISSUE THREAD

**Issue by WaffleBunny** [Wilyicaro/BetterFurnacesReforged#81]
so i placing furnace and there is a black pink squares

**Comment by WaffleBunny** [comment]
![2023-03-22_20 00 45](https://user-images.githubusercontent.com/108595088/226946502-a813f109-6b7a-4f30-8cca-d0579e4c236f.png)

**Comment by WaffleBunny** [comment]
all furnaces expect forges and upgrades

**Comment by Wilyicaro** [comment]
Inform the used version of the mod, as there are no problems with missing models of the furnaces in the current version of 1.19.3 (0.2.2), both for Fabric and Forge

**Comment by WaffleBunny** [comment]
> Inform the used version of the mod, as there are no problems with missing models of the furnaces in the current version of 1.19.3 (0.2.2), both for Fabric and Forge

Mod Version is 0.2.2 
MC version is 1.19.3

**Comment by Wilyicaro** [comment]
Due to lack of information, I cannot observe the occurrence of this error in any situation tested by me, if you want to help in fixing this error, send the mods used, some resourcepack used in the game and the Mod Loader used (Fabric or Forge)
