### ISSUE TITLE
Crash when i hover over generator upgrade in REI

### ISSUE THREAD

**Issue by Aurytis11** [Wilyicaro/BetterFurnacesReforged#85]
0.2.0-1.19.2
Fabric loader version 0.14.14

Bug/Glitch Occurrence Context
It always crashes no matter what i do if i hover over the generator upgrade in REI

What happened wrong
It crashed when i hovered over generator upgrade in REI
[crash-2023-04-04_20.32.23-client.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11151609/crash-2023-04-04_20.32.23-client.txt)

**Comment by Wilyicaro** [comment]
Thanks for reporting this crash, however I will have to move it to the FactoryAPI repository as it is not related to Better Furnaces Reforged.
Also, I see the API version is outdated, please update to the latest version(1.6.1) to get it working
