### ISSUE TITLE
Project MMO error with BFR. Log below.

### ISSUE THREAD

**Issue by ImN3k0** [Wilyicaro/BetterFurnacesReforged#87]
[crash-2023-04-22_08.28.32-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11301354/crash-2023-04-22_08.28.32-server.txt)

**Comment by Wilyicaro** [comment]
This error will be fixed in version 1.16.5-2.0.1, there was just a change in the ProjectMMO source code, which changed the furnace method
