### ISSUE TITLE
[Bug/Glitch] Game crashes upon trying to load world containing the ultimate forge

### ISSUE THREAD

**Issue by cmar7945** [Wilyicaro/BetterFurnacesReforged#88]
*Italic* = Optional

Betterfurnaces Reforged 1.19.4-0.10 MC version 1.19.4

Fabric Modloader 0.14.19

**Bug/Glitch Occurrence Context** Ticking

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-04-30 15:51:25
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.transfer.v1.storage.Storage.iterator()" because "other" is null
	at wily.betterfurnaces.fabric.BetterFurnacesPlatformImpl.smeltingAutoIO(BetterFurnacesPlatformImpl.java:40)
	at wily.betterfurnaces.BetterFurnacesPlatform.smeltingAutoIO(BetterFurnacesPlatform.java)
	at wily.betterfurnaces.blockentity.SmeltingBlockEntity.tick(SmeltingBlockEntity.java:551)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:665)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:719)
	at net.minecraft.class_1937.method_18471(class_1937.java:478)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at wily.betterfurnaces.fabric.BetterFurnacesPlatformImpl.smeltingAutoIO(BetterFurnacesPlatformImpl.java:40)
	at wily.betterfurnaces.BetterFurnacesPlatform.smeltingAutoIO(BetterFurnacesPlatform.java)
	at wily.betterfurnaces.blockentity.SmeltingBlockEntity.tick(SmeltingBlockEntity.java:551)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:665)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:719)
	at net.minecraft.class_1937.method_18471(class_1937.java:478)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
	Name: betterfurnacesreforged:ultimate_forge // wily.betterfurnaces.blockentity.ForgeBlockEntity
	Block: Block{betterfurnacesreforged:ultimate_forge}[colored=false,facing=up,lit=false,waterlogged=false]
	Block location: World: (-703,70,412), Section: (at 1,6,12 in -44,4,25; chunk contains blocks -704,-64,400 to -689,319,415), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Block: Block{betterfurnacesreforged:ultimate_forge}[colored=false,facing=up,lit=false,waterlogged=false]
	Block location: World: (-703,70,412), Section: (at 1,6,12 in -44,4,25; chunk contains blocks -704,-64,400 to -689,319,415), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:665)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:719)
	at net.minecraft.class_1937.method_18471(class_1937.java:478)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-608,79,240), Section: (at 0,15,0 in -38,4,15; chunk contains blocks -608,-64,240 to -593,319,255), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Level time: 501047 game time, 342249 day time
	Level name: Fabric Survival 2
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3657430144 bytes (3487 MiB) / 8547991552 bytes (8152 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3161
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m
	Fabric Mods: 
		ad_astra: Ad Astra 1.14.1
		architectury: Architectury 8.1.79
		balm-fabric: Balm 6.0.2
		betterfurnacesreforged: BetterFurnaces Reforged 1.19.4-0.1.0
		botarium: Botarium 2.0.5
		cardinal-components: Cardinal Components API 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-block: Cardinal Components API (blocks) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.54
		computercraft: CC: Tweaked 1.104.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_jcraft_jzlib: jzlib 1.1.3
			io_netty_netty-codec-http: netty-codec-http 4.1.82.Final
			org_squiddev_cobalt: Cobalt 0.7.0
		cookingforblockheads: Cooking for Blockheads 15.0.1
		copper_pipe: Simple Copper Pipes 1.13
		customspawns: Custom Spawns 0.8+1.19.4
		dark-enchanting: Dark Enchanting 1.0.1+1.19.4
			libgui: LibGui 7.0.0-beta.2+1.19.4
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
			omega-config: OmegaConfig 1.2.3-1.18.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 4.0
		experiencebugfix: Experience Bug Fix 19
		extractinator: Extractinator 2.1.0
		fabric-api: Fabric API 0.79.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.24+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.25+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.7+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.6+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.34+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.15+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.27+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.6+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.44+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.54+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.9+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.1+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.15+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.0+6cebf059f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.45+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.13+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.43+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.52+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.33+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.17+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.5+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.33+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.31+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.15+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.27+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.31+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.1+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.39+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.30+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.1+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.41+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.3+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.23+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.8+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.0+670e8ac6f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.5+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.1+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.38+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.28+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.21+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.41+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.1+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.1+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.2+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.45+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.20+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.9+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.1+da9bb835f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.3+63b515f4f4
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabricloader: Fabric Loader 0.14.19
		factory_api: Factory API 1.19.4-0.1.6.1
			team_reborn_energy: Energy 2.3.0
		fscript: FScript Lib 3.1.8
		handcrafted: Handcrafted 2.2.0
		iris: Iris 1.6.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre12
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemcollectors: Item Collectors 1.1.7
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 13.1.0.6
		journeymap: Journeymap 5.9.5
			journeymap-api-fabric: JourneyMap API 1.19.4-1.9-fabric-SNAPSHOT
		laserbridges: LaserBridges 1.19.4-1
		mcwbridges: Macaw's Bridges 2.0.7
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwfurnitures: Macaw's Furniture 3.1.0
		mcwroofs: Macaw's Roofs 2.2.3
		minecraft: Minecraft 1.19.4
		pfm: Paladin's Furniture 1.1.3
		quarryplus: QuarryPlus 19.3.754
		resourcefulconfig: Resourcefulconfig 1.2.0
		resourcefullib: Resourceful Lib 1.3.1
			com_teamresourceful_yabn: yabn 1.0.2
		sodium: Sodium 0.4.10+build.24
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.6
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.7
		survivalflight: Survival Flight 1.3.2
			tf_ssf_sfort_ini_sf-ini: SF-INI 1
		tesseract: Tesseract 1.0.32a
		toms_storage: Tom's Simple Storage Mod 1.5.5
		travelersbackpack: Traveler's Backpack 1.19.4-8.4.2
			reach-entity-attributes: Reach Entity Attributes 2.3.2
		treeharvester: Tree Harvester 8.0
		waystones: Waystones 13.0.1
		worldedit: WorldEdit 7.2.14+6360-094b734
		worldeditcui: WorldEditCUI 1.19.4+01
	Loaded Shaderpack: SEUS-Renewed-v1.0.1.zip
		Profile: Custom (+2 options changed by user)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, fabric, update_1_20
	Enabled Feature Flags: minecraft:update_1_20, minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.19-1.19.4

**What happened wrong** Game Crashes now upon opening world, due to ticking block entity

**Comment by Wilyicaro** [comment]
Thanks a lot for reporting this crash, the bug is simple and will be fixed soon in 1.19.4-0.1.1
