### ISSUE TITLE
Crash when trying to open furnace/forge gui

### ISSUE THREAD

**Issue by Aurytis11** [Wilyicaro/BetterFurnacesReforged#89]
Mod version 0.2.1 Minecraft 1.19.2

Mod Loader Version 0.14.14

**Bug/Glitch Occurrence Context** 
Game completely crashed when i tried to open the furnace gui.

*Crash Report [crash-2023-05-02_17.07.21-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11374080/crash-2023-05-02_17.07.21-server.txt)

**What happened wrong**
Game crashed for i don't know what reason when i tried to open the furnace gui.

**Comment by Wilyicaro** [comment]
It's not a BFR issue, just update your Fabric API to the latest version
