### ISSUE TITLE
1.19.4 mining problem

### ISSUE THREAD

**Issue by tuyilmaz** [Wilyicaro/BetterFurnacesReforged#90]
It is really slow when mining a block using pickaxe and when mining is done it doesn't drop the block(mining stone with wooden and stone pickaxe). Mods:
-architectury-8.1.80-forge
-BetterFurnaces-Forge-1.19.4-0.1.0
-FactoryAPI-Forge-1.19.4-0.1.6.1
-jei-1.19.4-forge-13.1.0.9
-OptiFine_1.19.4_HD_U_I4_MOD
Forge version: 45.0.59

**Comment by tuyilmaz** [comment]
After removing optifine and jei my game started to crash.
I downloaded forge 45.0.63
[Crash Log](https://pastebin.com/raw/tbf6nyPY)
[Latest Log](https://pastebin.com/raw/Ns2w3yC6)

**Comment by Wilyicaro** [comment]
Sorry for the long delay in support. 
Did you disable the Ultimate Furnaces addon in settings? There may be a bug in the tags that make it possible to mine the blocks, as the addon's furnaces and forges are not present, this tag is not loaded, and it is not even possible to have drops when mining the blocks.

About the issue of the mod causing a crash after removing these mods, there is no specific relation, just a bug in the registration of the blocks, which is using the Turkish alphabet, probably, will be fixed soon

**Comment by Wilyicaro** [comment]
About the "mining problem" , it has been partially fixed as of versions 1.19.4-1.1 and 1.20.1-1.0
