### ISSUE TITLE
[Bug] Standard Ore Proccessing Upgrade doesn't

### ISSUE THREAD

**Issue by Pop000100** [Wilyicaro/BetterFurnacesReforged#92]
0.1.0-1.19.4
Fabric 0.14.21
Raw Iron isn't being doubled in a Iron furnace

Client Log
[latest.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11608702/latest.log)
server Log
[server.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11608708/server.log)

**Comment by Wilyicaro** [comment]
I can't prove or verify this bug just with your game logs, I don't see a problem with duplicating raw ores in this version in my tests.
