### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by SCPRedMage** [Wilyicaro/BetterFurnacesReforged#93]
**Mod Version-Minecraft Version**
1.19.2-0.2.1
Mod Loader Version
Fabric 0.14.21

**Bug/Glitch Occurrence Context**
Modrinth page indicates this version should require Architectury version 6.5.85+fabric, but on starting with that version installed Fabric indicates it requires version 6.5.69, as is listed in the fabric.mod.json in the JAR file. The mod seems to work fine if the JSON is changed to specify 6.5.85.

**Comment by Wilyicaro** [comment]
Thanks for reporting the bug, it is known and will be fixed as soon as I have time to work on the mod
