### ISSUE TITLE
[Bug/Glitch] Auto-Input/Output/Factory upgrades causing crashes when adjacent to certain Create blocks

### ISSUE THREAD

**Issue by SCPRedMage** [Wilyicaro/BetterFurnacesReforged#95]
**Mod Version-Minecraft Version**
Minecraft 1.19.2, Better Furnaces Reforged v0.2.1
Mod Loader Version
Fabric 0.14.21

**Bug/Glitch Occurrence Context**
Server crashes when Auto-Input/Output/Factory upgraded furnaces are adjacent to various blocks such as Create fluid tanks or the Alternator from Create Crafts & Additions.

*Crash Report
[crash-2023-06-20_21.22.29-server.txt](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11812316/crash-2023-06-20_21.22.29-server.txt)

**What happened wrong**
I believe the issue is related to the fact that you're calling `other.iterator()` on line 40 of `fabric/BetterFurnacesPlatformImpl.java`, immediately *before* checking for `other` being `null`; Moving this after the check should fix these crashes.

**Comment by Wilyicaro** [comment]
This is exactly the bug you pointed out, it has been fixed in the later minecraft versions of the mod.
It will be fixed in 1.19.2-0.3, in the update that will bring the features of 1.19.4-0.1.3 :)
