### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by Alela12121** [Wilyicaro/BetterFurnacesReforged#96]
_1.20.1_

_Forge_ 47.0.19

Says that isn't compatible with pmmo version for 1.20.1.

![image](https://github.com/Wilyicaro/BetterFurnacesReforged/assets/137585303/74f66bbd-4a62-41c0-95ec-c958ce279f1d)

Actually the version of pmmo is 1.20.1-1.0.1

**Comment by Wilyicaro** [comment]
Sorry for the delay to reply
Fixed in 1.20.1-0.1.5, if you have more problems, just report :)
