### ISSUE TITLE
[Bug/Glitch]

### ISSUE THREAD

**Issue by Jeichacker** [Wilyicaro/BetterFurnacesReforged#98]
1.20.1

Fabric 0.14.21

[latest.log](https://github.com/Wilyicaro/BetterFurnacesReforged/files/11861374/latest.log)

When i log into my world in about 30 seconds to a minute this mod makes my pc freeze every 5 seconds and then recover repeatedly, if i remove the mod everythings fine again. The features of the mod all work so im not sure whats wrong.

**Comment by nevercamearound** [comment]
same with me but with forge

**Comment by Wilyicaro** [comment]
> same with me but with forge

I'm pretty sure your bug case isn't the same as his... 
At least what you reported there is the presence of a crash when loading the mod
